
const startZeit = Date.now();

var vor = [
'Abflugring ',
'Abtsgäßchen ',
'Achenbachstr. ',
'Ackermannstr. ',
'Adalbert-Stifter-Str. ',
'Adalbertstr. ',
'Adam-Heinstadt-Str. ',
'Adam-Leis-Str. ',
'Adam-Opel-Str. ',
'Adam-Riese-Str. ',
'Adelheidstr. ',
'Adelonstr. ',
'Adickesallee ',
'Adlerflychtplatz ',
'Adlerflychtstr. ',
'Adlhochplatz ',
'Adolf-Haeuser-Str. ',
'Adolf-Leweke-Str. ',
'Adolf-Meyer-Str. ',
'Adolf-Miersch-Str. ',
'Adolf-Reichwein-Str. ',
'Adolfstr. ',
'Adolph-Prior-Str. ',
'Affentorplatz ',
'Agendawaldschneise ',
'Ahornschneise ',
'Ahornschneise ',
'Ahornstr. ',
'Ährenstr. ',
'Ahrtalstr. ',
'Airport City Mall ',
'Airportring ',
'Akazienstr. ',
'Albanusstr. ',
'Albert-Blank-Str. ',
'Albert-Einstein-Str. ',
'Albert-Linel-Str. ',
'Albert-Schweitzer-Str. ',
'Albusstr. ',
'Alemannenweg ',
'Alexander-Riese-Weg ',
'Alexander-Todd-Str. ',
'Alexanderstr. ',
'Alfred-Brehm-Platz ',
'Alfred-Delp-Str. ',
'Alfred-Göbel-Weg ',
'Alfred-Kiefer-Weg ',
'Alfred-Pfaff-Str. ',
'Alfred-Wegener-Str. ',
'Alkmenestr. ',
'Allendorfer Str. ',
'Allerheiligenstr. ',
'Allerheiligentor ',
'Allesinastr. ',
'Allmeygang ',
'Alois-Brisbois-Weg ',
'Alois-Eckert-Str. ',
'Alpenroder Str. ',
'Alsfelder Str. ',
'Alt-Bergen ',
'Alt-Bonames ',
'Alt-Bornheim ',
'Alt-Enkheim ',
'Alt-Erlenbach ',
'Alt-Eschersheim ',
'Alt-Fechenheim ',
'Alt-Ginnheim ',
'Alt-Griesheim ',
'Alt-Harheim ',
'Alt-Hausen ',
'Alt-Heddernheim ',
'Alt-Höchst ',
'Alt-Kalbach ',
'Alt-Nied ',
'Alt-Niedereschbach ',
'Alt-Niederursel ',
'Alt-Praunheim ',
'Alt-Preungesheim ',
'Alt-Rödelheim ',
'Alt-Schwanheim ',
'Alt-Seckbach ',
'Alt-Sindlingen ',
'Alt-Sossenheim ',
'Alt-Zeilsheim ',
'Alte Brücke ',
'Alte Deisfeldschneise ',
'Alte Fahrt ',
'Alte Falterstr. ',
'Alte Gasse ',
'Alte Gelnhäuser Str. ',
'Alte Hofgasse ',
'Alte Mainzer Gasse ',
'Alte Mainzer Schneise ',
'Alte Niddabrücke ',
'Alte Riedbergstr. ',
'Alte Rothofstr. ',
'Altebergs-Zwerchgäßchen ',
'Altebergsweg ',
'Altebornstr. ',
'Alteichenweg ',
'Altenburger Weg ',
'Altenhainer Str. ',
'Altenhöferallee ',
'Altenhöferallee ',
'Alter Gundweg ',
'Alter Schulpfad ',
'Alter Wartweg ',
'Altes Schützenhüttengäßchen ',
'Altheegschneise ',
'Altheegschneise ',
'Altheimstr. ',
'Altkönigblick ',
'Altkönigstr. ',
'Altvaterstr. ',
'Alzeyer Str. ',
'Am Abtshof ',
'Am Alten Schloß ',
'Am Alten See ',
'Am Alten Volkshaus ',
'Am Ameisenberg ',
'Am Atzelberg ',
'Am Auerborn ',
'Am Auweg ',
'Am Bachberg ',
'Am Bächelchen ',
'Am Bahndamm ',
'Am Berger Spielhaus ',
'Am Bienenstock ',
'Am Bier ',
'Am Bonifatiusbrunnen ',
'Am Bonifatiusbrunnen ',
'Am Börnchen ',
'Am Bornheimer Hang ',
'Am Bornheimer Hang ',
'Am Borsdorfer ',
'Am Brennhaus ',
'Am Brückengarten ',
'Am Brünnchen ',
'Am Brunnengarten ',
'Am Buchbaum ',
'Am Buchwald ',
'Am Burghof ',
'Am Büttelstück ',
'Am Dachsberg ',
'Am Dammgraben ',
'Am Dammgraben ',
'Am Dorfgarten ',
'Am Dornbusch ',
'Am Ebelfeld ',
'Am Eckenheimer Friedhof ',
'Am Eichbaum ',
'Am Eichenloh ',
'Am Eisernen Schlag ',
'Am Eiswerk ',
'Am Elektrizitätswerk ',
'Am Ellerfeld ',
'Am Enkheimer Steg ',
'Am Entenpfad ',
'Am Erlenbruch ',
'Am Eschbachtal ',
'Am Eschersheimer Abtshof ',
'Am Faulbrunnen ',
'Am Felsenkeller ',
'Am Fischstein ',
'Am Fischwehr ',
'Am Flughafen ',
'Am Försterpfad ',
'Am Forum ',
'Am Gabelacker ',
'Am Galgen ',
'Am Gansbühel ',
'Am Geistpförtchen ',
'Am Gemeindegarten ',
'Am Ginnheimer Hang ',
'Am Ginnheimer Wäldchen ',
'Am Gisisberg ',
'Am Goldsteinpark ',
'Am Graben ',
'Am Großen Berge ',
'Am Grünen Graben ',
'Am Grünhof ',
'Am Günthersbrunnen ',
'Am Hang ',
'Am Hasensprung ',
'Am Hauptbahnhof ',
'Am Henninger Turm ',
'Am Hennsee ',
'Am Herrenhof ',
'Am Hessen-Center ',
'Am Hessenborn ',
'Am Himmerich ',
'Am Hirtenacker ',
'Am Hochwehr ',
'Am Hofgut ',
'Am Hofgut Goldstein ',
'Am Hohen Weg ',
'Am Hohlacker ',
'Am Höhstock ',
'Am Höllenberg ',
'Am Hollerbusch ',
'Am Hollgraben ',
'Am Höllsteg ',
'Am Holzpförtchen ',
'Am Honigberg ',
'Am Hopfenbrunnen ',
'Am Hopfengarten ',
'Am Hühnerberg ',
'Am Industriehof ',
'Am Jessenapfel ',
'Am Kalten Berg ',
'Am Kapellenberg ',
'Am Kappelgarten ',
'Am Kiesberg ',
'Am Kirchberg ',
'Am Kirchholz ',
'Am Klarapfel ',
'Am Klingelborn ',
'Am Königshof ',
'Am Köstrich ',
'Am Kreuz ',
'Am Kunzengarten ',
'Am Lachgraben ',
'Am Lausberg ',
'Am Lehenweg ',
'Am Leinritt ',
'Am Leisrain ',
'Am Leonhardsbrunn ',
'Am Leonhardstor ',
'Am Lindenbaum ',
'Am Lindenfeld ',
'Am Lohrberg ',
'Am Lohwald ',
'Am Luftbrückendenkmal ',
'Am Mainbörnchen ',
'Am Mainplacken ',
'Am Markstein ',
'Am Martinszehnten ',
'Am Michlersbrunnen ',
'Am Mispelbusch ',
'Am Mittelpfad ',
'Am Mühlgarten ',
'Am Mühlgewann ',
'Am Mühlkanal ',
'Am Neuenberg ',
'Am Neufeld ',
'Am Niddatal ',
'Am Niedwald ',
'Am Nonnenhof ',
'Am Oberforsthaus ',
'Am Oberschlag ',
'Am Ohlenstück ',
'Am Pfingstlohr ',
'Am Pohlsberg ',
'Am Poloplatz ',
'Am Posthorn ',
'Am Rebenborn ',
'Am Reinhardshof ',
'Am Riederbruch ',
'Am Riedgraben ',
'Am Riedsteg ',
'Am Rödelheimer Wehr ',
'Am Römerbrunnen ',
'Am Römerhof ',
'Am Rosenberg ',
'Am Rosengarten ',
'Am Roten Graben ',
'Am Rötheneck ',
'Am Ruhestein ',
'Am Rütschlehen ',
'Am Saalenbusch ',
'Am Salusbach ',
'Am Salzhaus ',
'Am Sandberg ',
'Am Satz ',
'Am Sausee ',
'Am Schieferstein ',
'Am Schießrain ',
'Am Schlittenberg ',
'Am Schwalbenschwanz ',
'Am Schwemmteich ',
'Am Seedamm ',
'Am Selzerbrunnen ',
'Am Siechen ',
'Am Siegesbaum ',
'Am Sportplatz Höchst ',
'Am Spritzenhaus ',
'Am Sprudel ',
'Am Städelshof ',
'Am Stadtpark ',
'Am Steinberg ',
'Am Steinernen Kreuz ',
'Am Steinernen Stock ',
'Am Stiegelschlag ',
'Am Stockborn ',
'Am Strandbad Höchst ',
'Am Tiergarten ',
'Am Traubengarten ',
'Am Treutengraben ',
'Am Ulmenrück ',
'Am Ulmenstückweg ',
'Am Urselbach ',
'Am Villaberg ',
'Am Vogelherd ',
'Am Waldacker ',
'Am Wäldchen ',
'Am Waldgraben ',
'Am Wasserpark ',
'Am Wassertempel ',
'Am Wasserturm ',
'Am Weidenbaum ',
'Am Weidenbusch ',
'Am Weidenwörth ',
'Am Weigelsgarten ',
'Am Weimarfloß ',
'Am Weingarten ',
'Am Weißberg ',
'Am Weißen Stein ',
'Am Weißen Turm ',
'Am Weißkirchener Berg ',
'Am Wendelsgarten ',
'Am Wetterhahn ',
'Am Wiesenhof ',
'Am Wiesenrain ',
'Am Wildpfad ',
'Am Wingert ',
'Am Wingertsgrund ',
'Am Zedernholz ',
'Am Ziehgraben ',
'Amaliestr. ',
'Ambronenpfad ',
'Amelia-Mary-Earhart-Str. ',
'Ammelburgstr. ',
'Amöneburger Str. ',
'Amorbacher Weg ',
'Amperestr. ',
'Amselweg ',
'Amtsgasse ',
'an Den Bangerten ',
'An den Bergen ',
'An den Drei Brunnen ',
'an Den Drei Hohen ',
'An den Drei Steinen ',
'An Den Flesch-Werken ',
'An den Geiselwiesen ',
'An den Gerlachswiesen ',
'An den Kaiserpappeln ',
'an Den Katharinenhöfen ',
'An den Mühlwegen ',
'An den Pappeln ',
'An den Pflanzländern ',
'An den Postwiesen ',
'An den Riederhöfen ',
'An den Röthen ',
'An den Schießgärten ',
'An den Weiden ',
'An der Alten Gießerei ',
'an Der Alten Ziegelei ',
'An der Bergstr. ',
'An der Bitz ',
'An der Bleiche ',
'An der Bornhohl ',
'An der Dammheide ',
'An der Fähre ',
'An der Festeburg ',
'An der Fischerweide ',
'an Der Goetheruh ',
'An der Gruckau ',
'An der Grünhohl ',
'An der Hauptwache ',
'An der Herrenwiese ',
'An der Kleinmarkthalle ',
'An der Kreuzheck ',
'an Der Landwehr ',
'An der Lindenallee ',
'An der Litzelwiese ',
'An der Lühe ',
'An Der Mainkur ',
'An der Mannsfaust ',
'an Der Marienkirche ',
'An der Nachtweide ',
'An der Nidda ',
'An der Oberen Lache ',
'An der Oberpforte ',
'An der Pfaffenmauer ',
'An der Pfarrwiese ',
'An der Praunheimer Mühle ',
'An der Ringmauer ',
'An der Roseneller ',
'an Der Rosenkranzkirche ',
'an Der Rotterdamer Werft ',
'An der Ruhbank ',
'An Der Sandelmühle ',
'An der Schwarzbachmühle ',
'An der Seehecke ',
'An der Staufenmauer ',
'An der Staustufe ',
'An der Steinmühle ',
'An der Tillylinde ',
'An der Walkmühle ',
'An der Wehrmauer ',
'an Der Welle ',
'An der Wellenburg ',
'An der Wildhube ',
'An der Wolfsweide ',
'An der Wörthspitze ',
'An der Zingelswiese ',
'Andersenweg ',
'Andreaestr. ',
'Andreasstr. ',
'Anemonenpfad ',
'Angelika-Machinek-Str. ',
'Ankergasse ',
'Ankunftbogen ',
'Anna-Beyer-Str. ',
'Anna-Lindh-Allee ',
'Annabergstr. ',
'Annastr. ',
'Anne-Frank-Str. ',
'Anneliese-Hoevel-Str. ',
'Annemarie-Schlordt-Str. ',
'Annette-Kolb-Weg ',
'Anspacher Str. ',
'Anton-Burger-Weg ',
'Anton-Radl-Pfad ',
'Anton-Schlüter-Str. ',
'Antoninusstr. ',
'Antoniterstr. ',
'Anzengruberstr. ',
'Apoldaer Weg ',
'Apostelstr. ',
'Appelsgasse ',
'Arabella-Passage ',
'Aralienstr. ',
'Arndtstr. ',
'Arnoldshainer Str. ',
'Arnoldstr. ',
'Arnsburger Str. ',
'Arnstädter Weg ',
'Arnsteiner Str. ',
'Arnswalder Str. ',
'Arolser Str. ',
'Arthur-Von-Weinberg-Str. ',
'Aschaffenburger Str. ',
'Aschebachstr. ',
'Aßlarer Str. ',
'Aßmannshäuser Weg ',
'Assenheimer Str. ',
'Astronomenweg ',
'Athener Str. ',
'Atzelbergplatz ',
'Atzelbergstr. ',
'Auerbacher Str. ',
'Auerfeldstr. ',
'Auerhahnstr. ',
'Auerstr. ',
'Auerswaldstr. ',
'Auerweg ',
'Auf dem Berg ',
'Auf dem Gleichen ',
'Auf dem Lohr ',
'Auf dem Mühlberg ',
'Auf dem Ried ',
'Auf dem Schafberg ',
'Auf der Beun ',
'Auf der Insel ',
'Auf der Körnerwiese ',
'Auf der Kuhr ',
'Auf der Lindenhöhe ',
'Auf der Platte ',
'Auf der Sandeller ',
'Auf Der Sandkaute ',
'Auf der Schanz ',
'Auf der Schloßhecke ',
'Auf der Steinern Str. ',
'Auf der Steinritz ',
'Auf der Waldhohl ',
'Auf die Bach ',
'Augrabenweg ',
'August-Bebel-Str. ',
'August-Euler-Str. ',
'August-Schanz-Str. ',
'August-Scheidel-Str. ',
'August-Siebert-Str. ',
'Augustenburgstr. ',
'Augustusstr. ',
'Aulmannstr. ',
'Aussiger Str. ',
'Autogenstr. ',
'Aystettstr. ',
'Azaleenweg ',
'B-Ebene ',
'Babenhäuser Landstr. ',
'Bachflussweg ',
'Bachforellenweg ',
'Bachmannstr. ',
'Bachrain ',
'Bachstelzenweg ',
'Bachstr. ',
'Bachweg ',
'Bachwiesenstr. ',
'Bäckergasse ',
'Bäckerweg ',
'Badstubengasse ',
'Baeyerstr. ',
'Bahnhof Berkersheim ',
'Bahnhof Frankfurter Berg ',
'Bahnhof Louisa ',
'Balduinstr. ',
'Barbarossastr. ',
'Barchfeldstr. ',
'Barckhausstr. ',
'Bärenstr. ',
'Bärenstr. ',
'Barfüßergasse ',
'Barodapfad ',
'Bartholomäusgasse ',
'Baruch-Baschwitz-Platz ',
'Basaltstr. ',
'Baseler Platz ',
'Baseler Str. ',
'Baskin - Road ',
'Baskin Road ',
'Bathgartenweg ',
'Battenberger Weg ',
'Batterie ',
'Battonnstr. ',
'Bauhofstr. ',
'Baumertstr. ',
'Baumweg ',
'Baustr. ',
'Bebraer Str. ',
'Bechtenwaldstr. ',
'Beckerserlen ',
'Beckerweg ',
'Beethovenplatz ',
'Beethovenstr. ',
'Belchenstr. ',
'Ben-Gurion-Ring ',
'Bendelgasse ',
'Bendergasse ',
'Benzengrundschneise ',
'Benzengrundweg ',
'Berberitzenweg ',
'Berberitzenweg ',
'Berger Marktplatz ',
'Berger Rathausplatz ',
'Berger Schützenhaus ',
'Berger Str. ',
'Berger Str. ',
'Berger Weg ',
'Bergesgrundweg ',
'Bergmannweg ',
'Bergweg ',
'Berkersheimer Bahnstr. ',
'Berkersheimer Hohl ',
'Berkersheimer Obergasse ',
'Berkersheimer Untergasse ',
'Berkersheimer Weg ',
'Berliner Str. ',
'Bernadottestr. ',
'Bernburger Weg ',
'Berner Str. ',
'Bernhard-Becker-Str. ',
'Bernhard-Grzimek-Allee ',
'Bernhard-Hermkes-Str. ',
'Bernhard-Mannfeld-Weg ',
'Bernusstr. ',
'Bert-Brecht-Str. ',
'Bertha-Bagge-Str. ',
'Bertha-von-Suttner-Ring ',
'Bertholdstr. ',
'Bertramstr. ',
'Bertramswiese ',
'Beselerstr. ',
'Bessemerstr. ',
'Bessie-Coleman-Str. ',
'Bethmann-Hollweg-Str. ',
'Bethmannstr. ',
'Bettinaplatz ',
'Bettinastr. ',
'Betzdorfer Str. ',
'Beunestr. ',
'Beuthener Str. ',
'Bickelhof ',
'Bickenbacher Weg ',
'Biebergasse ',
'Biedenkopfer Weg ',
'Biegweg ',
'Bielefelder Str. ',
'Bildäckerstr. ',
'Billtalstr. ',
'Bilsteinweg ',
'Bindingstr. ',
'Bingelsweg ',
'Birkenwäldchen ',
'Birkenweg ',
'Birkholzweg ',
'Birminghamstr. ',
'Birsteiner Str. ',
'Bischofsheimer Platz ',
'Bischofsheimer Str. ',
'Bischofsheimer Weg ',
'Bischofsweg ',
'Bitterfelder Weg ',
'Blanchardstr. ',
'Blankenburger Weg ',
'Blankenheimer Str. ',
'Blauenstr. ',
'Blauglockenweg ',
'Blauhandgasse ',
'Blauländchenstr. ',
'Blauwiesenweg ',
'Bleichgartengässchen ',
'Bleichstr. ',
'Bleidenstr. ',
'Bleiweißstr. ',
'Blumenstr. ',
'Blütenweg ',
'Bockenheimer Anlage ',
'Bockenheimer Landstr. ',
'Bockenheimer Landstr. ',
'Bockenheimer Warte ',
'Bockenheimer Wiesenweg ',
'Böcklinstr. ',
'Bodelschwinghstr. ',
'Bodenbacher Weg ',
'Bodenseestr. ',
'Bodenstedtstr. ',
'Bodenweg ',
'Bohlenfeldschneise ',
'Bohlenweg ',
'Böhmerstr. ',
'Bohnenstückschneise ',
'Bolongarostr. ',
'Bommersheimer Str. ',
'Bonameser Hainstr. ',
'Bonameser Hintergasse ',
'Bonameser Mittelgasse ',
'Bonameser Str. ',
'Bonifatiusstr. ',
'Bönstädter Str. ',
'Bornemannstr. ',
'Börneplatz ',
'Bornheimer Landstr. ',
'Bornheimer Landwehr ',
'Bornhof ',
'Bornweg ',
'Bornweidstr. ',
'Bornwiesenweg ',
'Börsenplatz ',
'Börsenstr. ',
'Borsigallee ',
'Boseweg ',
'Boskoopstr. ',
'Boßstr. ',
'Bottenhorner Weg ',
'Böttgerstr. ',
'Brahmsstr. ',
'Brand ',
'Brandenburger Weg ',
'Brandhöfchen ',
'Brandschneise ',
'Brandschneise ',
'Braubachstr. ',
'Braubachstr. ',
'Braumannstr. ',
'Braunfelsstr. ',
'Braunschweiger Weg ',
'Bregenzer Str. ',
'Breidensteiner Weg ',
'Breite Gasse ',
'Breitenbachbrücke ',
'Breitenbachstr. ',
'Breitlacherstr. ',
'Bremer Platz ',
'Bremer Str. ',
'Brendelstr. ',
'Brentanostr. ',
'Breslauer Str. ',
'Breubergstr. ',
'Breuerwiesenstr. ',
'Breulsweg ',
'Briandring ',
'Brohltalstr. ',
'Brombeerpfad ',
'Brommstr. ',
'Brönnerstr. ',
'Broßstr. ',
'Bruchfeldplatz ',
'Bruchfeldstr. ',
'Bruchstr. ',
'Brücke Des Halben Bootes ',
'Brückenstr. ',
'Brückhofstr. ',
'Brückschneise ',
'Brückschneise ',
'Brückweg ',
'Brüder-Grimm-Str. ',
'Brüder-Grimm-Str. ',
'Bruderhofstr. ',
'Brühlfeld ',
'Brühlstr. ',
'Brüningstr. ',
'Brunnenhof ',
'Brunnenpfad ',
'Brunnenstr. ',
'Brunnenweg ',
'Bruno-Poelke-Str. ',
'Bruno-Stürmer-Str. ',
'Brüsseler Str. ',
'Buber-Neumann-Weg ',
'Buchbornstr. ',
'Buchenhorster Hof ',
'Buchenrodestr. ',
'Buchenschneise ',
'Buchenstr. ',
'Buchgasse ',
'Buchrainplatz ',
'Buchrainschneise ',
'Buchrainstr. ',
'Buchsbaumweg ',
'Buchscheerfeldweg ',
'Buchwaldstr. ',
'Bückeburger Weg ',
'Budapester Str. ',
'Buddeschneise ',
'Büdinger Str. ',
'Bundenweg ',
'Bürgeler Str. ',
'Burgenlandweg ',
'Bürgerstr. ',
'Burgfriedenstr. ',
'Burggraben ',
'Burgholzer Platz ',
'Burgholzer Str. ',
'Burglehen ',
'Burgstr. ',
'Burgstr. ',
'Burgstr. ',
'Burgunderweg ',
'Burnitzstr. ',
'Bussardschneise ',
'Busstrecke ',
'Butzbacher Str. ',
'Butznickelweg ',
'Buzzistr. ',
'Cäcilienstr. ',
'Camberger Str. ',
'Camillo-Sitte-Weg ',
'Carbonestr. ',
'Cargo City Süd ',
'Carl-Barthel-Weg ',
'Carl-Benz-Str. ',
'Carl-Benz-Str. ',
'Carl-Goerdeler-Str. ',
'Carl-Heicke-Weg ',
'Carl-Hermann-Rudloff-Allee ',
'Carl-Schultis-Str. ',
'Carl-Sonnenschein-Str. ',
'Carl-Theodor-Reiffenstein-Platz ',
'Carl-Theodor-Reiffenstein-Platz ',
'Carl-Ulrich-Brücke ',
'Carl-von-Noorden-Platz ',
'Carl-von-Weinberg-Str. ',
'Carl-Weigert-Platz ',
'Carl-Zeiss-Str. ',
'Carlo-Schmid-Platz ',
'Cäsar-Von-Hofacker-Str. ',
'Casimirstr. ',
'Casparistr. ',
'Cassellastr. ',
'Celsiusplatz ',
'Centerschneise ',
'Centerschneise ',
'Cézanneweg ',
'Chamissostr. ',
'Charlotte-Schiffler-Str. ',
'Charlottenhof ',
'Chattenweg ',
'Cheruskerweg ',
'Christa-Maar-Str. ',
'Christiane-Vulpius-Str. ',
'Christiansweg ',
'Christoph-Knips-Str. ',
'Christusdornallee ',
'Cimbernweg ',
'Ciolfstr. ',
'Clara-Schumann-Weg ',
'Clematisweg ',
'Clemensstr. ',
'Clementineweg ',
'Coburger Weg ',
'Cohausenstr. ',
'Colmarer Str. ',
'Colsmanstr. ',
'Comeniusstr. ',
'Conrad-Weil-Gasse ',
'Cordierstr. ',
'Corneliusstr. ',
'Coventrystr. ',
'Cranachstr. ',
'Cretzschmarstr. ',
'Cronstettenstr. ',
'Crutzenkirchweg ',
'Cunostr. ',
'Cuxhavener Str. ',
'Dahlienstr. ',
'Dahlmannstr. ',
'Daimlerstr. ',
'Dalbergplatz ',
'Dalbergstr. ',
'Damaschkeanger ',
'Dammschneise ',
'Dammstr. ',
'Dammweg ',
'Danneckerstr. ',
'Dantestr. ',
'Danziger Platz ',
'Darmstädter Landstr. ',
'Darmstädter Landstr. ',
'Darmstädter Landstr. ',
'Das Stumpfe Gäßchen ',
'Däumling ',
'David-Stempel-Str. ',
'De-Bary-Str. ',
'De-Neufville-str. ',
'De-Ridder-Weg ',
'De-Saint-Exupéry-Str. ',
'Dehnhardtstr. ',
'Deidesheimer Str. ',
'Deisfeldschneise ',
'Den Haager Str. ',
'Denisweg ',
'Denisweg ',
'Denisweg ',
'Denzerstr. ',
'Derrerschneise ',
'Dessauer Weg ',
'Detmolder Platz ',
'Deuil-La-Barre-Str. ',
'Deutschherrenschneise ',
'Deutschherrnbrücke ',
'Deutschherrnschneise ',
'Deutschherrnufer ',
'Deutschordenstr. ',
'Diebsgrundweg ',
'Dieburger Str. ',
'Dielmannstr. ',
'Diemelstr. ',
'Dieselstr. ',
'Diesterwegplatz ',
'Diesterwegstr. ',
'Dietesheimer Str. ',
'Dietrich-Bonhoeffer-Weg ',
'Dietrichstr. ',
'Diezelschneise ',
'Diezer Str. ',
'Dillenburger Str. ',
'Dillgasse ',
'Distelrasen ',
'Ditmarstr. ',
'Dominikanergasse ',
'Domitianstr. ',
'Domplatz ',
'Domstr. ',
'Donnersbergstr. ',
'Dorfelder Str. ',
'Dorfwiesenweg ',
'Dornhöfer Schneise ',
'Dornholzhäuser Str. ',
'Dörnigheimer Str. ',
'Dörpfeldstr. ',
'Dörrwiesenstr. ',
'Dortelweiler Str. ',
'Dottenfeldstr. ',
'Drachengäßchen ',
'Draisbornstr. ',
'Dreieichschneise ',
'Dreieichstr. ',
'Dreihäusergasse ',
'Dreikönigsstr. ',
'Dreispitzstr. ',
'Drosselweg ',
'Droysenstr. ',
'Dubliner Str. ',
'Dufourstr. ',
'Duisbergstr. ',
'Dunantring ',
'Dunckerstr. ',
'Dungweg ',
'Dürerstr. ',
'Dürkheimer Str. ',
'Düsseldorfer Str. ',
'Ebereschenweg ',
'Eberhardstr. ',
'Ebersheimstr. ',
'Eberstadtstr. ',
'Ebertschneise ',
'Echzeller Str. ',
'Eckenheimer Landstr. ',
'Eckenheimer Landstr. ',
'Eckenheimer Landstr. ',
'Eckenheimer Schulstr. ',
'Eckernförder Str. ',
'Eckhardtstr. ',
'Eckstr. ',
'Edenkobener Str. ',
'Ederstr. ',
'Edingerweg ',
'Edisonstr. ',
'Edith-Stein-Weg ',
'Edmund-Rumpler-Str. ',
'Eduard-Bernstein-Weg ',
'Eduard-Rüppell-Str. ',
'Egelsbacher Str. ',
'Egenolffstr. ',
'Egerländer Str. ',
'Egestr. ',
'Ehemalige Auslagergasse ',
'Ehemalige Hainer Gasse ',
'Ehemaliger Frankenhofgang ',
'Ehemaliges Schwertfegergäßchen ',
'Ehingerstr. ',
'Eibenweg ',
'Eichendorffstr. ',
'Eichengrundschneise ',
'Eichenstr. ',
'Eichhörnchenpfad ',
'Eichwaldstr. ',
'Eifelstr. ',
'Einbaumstr. ',
'Einbiglerweg ',
'Einsiedlerstr. ',
'Eisenacher Weg ',
'Eiserfelder Str. ',
'Eiserne Hand ',
'Eiserner Steg ',
'Eiserner Steg ',
'Elbestr. ',
'Elbinger Str. ',
'Elefantengasse ',
'Elektronstr. ',
'Eleonore-Sterling-Str. ',
'Elisabeth-Winterhalter-Str. ',
'Elisabethenplatz ',
'Elisabethenstr. ',
'Elisabethenstr. ',
'Elkenbachstr. ',
'Ella-Bergmann-Michel-Str. ',
'Ella-Bergmann-Michel-Str. ',
'Ellerstr. ',
'Ellis Road ',
'Ellisroad ',
'Elly-Beinhorn-Str. ',
'Elly-Heuss-Knapp-Str. ',
'Elmer Weg ',
'Elsa-Brändström-Platz ',
'Else-Alken-Str. ',
'Else-Epstein-Weg ',
'Else-Kröner-Passage ',
'Elsheimerstr. ',
'Elsterstr. ',
'Eltviller Str. ',
'Emdener Str. ',
'Emil-Claar-Str. ',
'Emil-Sulzbach-Str. ',
'Emil-Von-Behring-Str. ',
'Emmerich-Josef-Str. ',
'Emmy-Klieneberger-Nobel-Str. ',
'Emsdorfer Str. ',
'Emser Brücke ',
'Emser Str. ',
'Endsbornstr. ',
'Enge Gasse ',
'Engelsplatz ',
'Engelsruhe ',
'Engelthaler Str. ',
'Enggasse ',
'Enkheimer Str. ',
'Eppenhainer Str. ',
'Eppsteiner Str. ',
'Eptingweg ',
'Erbacher Str. ',
'Erbbaustr. ',
'Erbsengasse ',
'Erfurter Weg ',
'Erich-Kästner-Str. ',
'Erich-Ollenhauer-Ring ',
'Erlenbacher Stadtweg ',
'Erlenbacher Str. ',
'Erlenseer Str. ',
'Erlenstr. ',
'Erna-Pinner-Str. ',
'Ernst-Abbe-Str. ',
'Ernst-Achilles-Platz ',
'Ernst-Balser-Str. ',
'Ernst-Heinkel-Str. ',
'Ernst-Kahn-Str. ',
'Ernst-Schwendler-Str. ',
'Ernst-Wiss-Str. ',
'Erntestr. ',
'Erstes Altebergsgäßchen ',
'Erstes Wartegäßchen ',
'Erzbergerstr. ',
'Erzenweg ',
'Eschborner Landstr. ',
'Eschenbachstr. ',
'Eschenheimer Anlage ',
'Eschenheimer Anlage ',
'Eschenheimer Tor ',
'Eschersheimer Landstr. ',
'Eschersheimer Landstr. ',
'Eschweger Str. ',
'Espenstr. ',
'Esperantostr. ',
'Esslinger Str. ',
'Ettlingerstr. ',
'Euckenstr. ',
'Eugen-Blanck-Str. ',
'Eugen-Hartmann-Str. ',
'Eugen-Kaufmann-Str. ',
'Eulengasse ',
'Eulenpfad ',
'Europa-Allee ',
'Europa-Allee ',
'Europabrücke ',
'Ewald-Heinrich-Von-Kleist-Platz ',
'Eysseneckschneise ',
'Eysseneckstr. ',
'Eyssenschneise ',
'Eyssenstr. ',
'Eytelweinstr. ',
'F 1 Freifläche ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F  ',
'F ',
'F ',
'F ',
'F ',
'F ',
'F ',
'F ',
'F ',
'F ',
'Fabian-Von-Schlabrendorff-Str. ',
'Fabriciusstr. ',
'Fachfeldstr. ',
'Fahrgasse ',
'Fahrtor ',
'Falkensteiner Str. ',
'Falkenweg ',
'Falkstr. ',
'Fallerslebenstr. ',
'Falltorstr. ',
'Familie-Jürges-Platz ',
'Familie-Jürges-Weg ',
'Farbenstr. ',
'Färberstr. ',
'Fasanenweg ',
'Faulborngasse ',
'Faulbrunnenweg ',
'Fechenheimer Leinpfad ',
'Fechenheimer Str. ',
'Feierabendweg ',
'Feldbergblick ',
'Feldbergstr. ',
'Feldgerichtstr. ',
'Feldscheidenstr. ',
'Felix-Dahn-Str. ',
'Felix-Kracht-Str. ',
'Felix-Wankel-Str. ',
'Fellnerstr. ',
'Felsenbirnenweg ',
'Ferdinand-Braun-Str. ',
'Ferdinand-Dirichs-Weg ',
'Ferdinand-Happ-Str. ',
'Ferdinand-Hofmann-Str. ',
'Ferdinand-Kramer-Str. ',
'Ferdinand-Porsche-Str. ',
'Ferdinand-Scholling-Ring ',
'Ferdinand-Schrey-Weg ',
'Festeburgring ',
'Feststr. ',
'Feuerbachstr. ',
'Feuerwehrstr. ',
'Feyerleinstr. ',
'Fichardstr. ',
'Fichtenschneise ',
'Fichtenschneise ',
'Fichtestr. ',
'Finkenhofstr. ',
'Finkenweg ',
'Finthener Weg ',
'Fischbacher Str. ',
'Fischerfeldstr. ',
'Fischerplätzchen ',
'Fischerweg ',
'Flaischlenstr. ',
'Flanbrechtstr. ',
'Flaschenburgstr. ',
'Fleckenbühlstr. ',
'Fleischergasse ',
'Flemming - Drive ',
'Flemming Drive ',
'Flensburger Str. ',
'Fliederweg ',
'Flinschstr. ',
'Florastr. ',
'Florianweg ',
'Flörsheimer Str. ',
'Florstädter Str. ',
'Flößerbrücke ',
'Flughafen Frankfurt Am Main ',
'Flughafenschneise ',
'Flughafenstr. ',
'Flurscheideweg ',
'Flußgasse ',
'Flusskrebssteg ',
'Flutgraben ',
'Fontanestr. ',
'Foockenstr. ',
'Försterwiesenweg ',
'François-Mitterrand-Platz ',
'Francstr. ',
'Frankenallee ',
'Frankenallee ',
'Frankensteiner Platz ',
'Frankensteiner Str. ',
'Frankenthaler Weg ',
'Frankfurt Airport-Center ',
'Franklinstr. ',
'Franz-Diehl-Weg ',
'Franz-Henle-Str. ',
'Franz-Kafka-Str. ',
'Franz-Lenbach-Str. ',
'Franz-Rücker-Allee ',
'Franz-Simon-Str. ',
'Franz-Werfel-Str. ',
'Franziska-Kessel-Str. ',
'Franziusplatz ',
'Franziusstr. ',
'Franzosenweg ',
'Frauenhofstr. ',
'Frauenlobstr. ',
'Frauensteinplatz ',
'Frauensteinstr. ',
'Freiherr-vom-Stein-Str. ',
'Freihofstr. ',
'Freiligrathstr. ',
'Freseniusstr. ',
'Fressgass ',
'Freudenberger Str. ',
'Frida-Amram-Weg ',
'Friedberger Anlage ',
'Friedberger Anlage ',
'Friedberger Landstr. ',
'Friedberger Landstr. ',
'Friedberger Platz ',
'Friedberger Tor ',
'Friedberger Tor ',
'Friedel-Schomann-Weg ',
'Friedensbrücke ',
'Friedensstr. ',
'Friedlebenstr. ',
'Friedrich-Bergius-Weg ',
'Friedrich-Dessauer-Str. ',
'Friedrich-Ebert-Anlage ',
'Friedrich-Ebert-Anlage ',
'Friedrich-Heyer-Weg ',
'Friedrich-Kahl-Str. ',
'Friedrich-Karl-Klausing-Str. ',
'Friedrich-List-Str. ',
'Friedrich-Manz-Weg ',
'Friedrich-Naumann-Str. ',
'Friedrich-Stampfer-Str. ',
'Friedrich-Stoltze-Platz ',
'Friedrich-Stoltze-Platz ',
'Friedrich-Wilhelm-Von-Steuben-Str. ',
'Friedrich-Wilhelm-von-Steuben-Str. ',
'Friedrichsdorfer Str. ',
'Friedrichstr. ',
'Friesengasse ',
'Friesstr. ',
'Fritschengäßchen ',
'Fritz-Bauer-Str. ',
'Fritz-Boehle-Str. ',
'Fritz-Erler-Str. ',
'Fritz-Klatte-Str. ',
'Fritz-Neumark-Weg ',
'Fritz-Reuter-Str. ',
'Fritz-Schubert-Ring ',
'Fritz-Schumacher-Weg ',
'Fritz-Tarnow-Str. ',
'Fritz-Wichert-Ring ',
'Fritzlarer Str. ',
'Fröbelstr. ',
'Frohngrundweg ',
'Froschhäuser Str. ',
'Frühmessereiweg ',
'Fuchshohl ',
'Fuchsienstr. ',
'Fuchsplattweg ',
'Fuchstanzstr. ',
'Fuldaer Str. ',
'Füllerstr. ',
'Funckstr. ',
'Fürstenbergerstr. ',
'Gabelsbergerstr. ',
'Gablonzer Str. ',
'Gabriel-Riesser-Weg ',
'Gagernstr. ',
'Galerie Des Duftenden Wassers ',
'Galgenstr. ',
'Gallusanlage ',
'Galluswarte ',
'Galvanistr. ',
'Ganghoferstr. ',
'Gangstr. ',
'Gänsseeweiherweg ',
'Garbenstr. ',
'Garküchenplatz ',
'Gartenschneise ',
'Gartenstr. ',
'Gartenstr. ',
'Gärtnerweg ',
'Gasleitungsschneise ',
'Gateway Gardens ',
'Gaugrafenstr. ',
'Gauguinweg ',
'Gaußstr. ',
'Gebeschusstr. ',
'Gebrüder-Hommel-Anlage ',
'Gebrüder-Wright-Str. ',
'Gederner Str. ',
'Gehespitzer Schneise ',
'Geibelstr. ',
'Geierskopfweg ',
'Geigerstr. ',
'Geißblattpfad ',
'Geiselsteinweg ',
'Geisenheimer Str. ',
'Geißspitzweg ',
'Gelastr. ',
'Gelbehirschstr. ',
'Geleitsstr. ',
'Gellertstr. ',
'Gelnhäuser Str. ',
'Gemündener Str. ',
'Genfer Str. ',
'Georg-Allgaier-Str. ',
'Georg-Baumgarten-Str. ',
'Georg-Büchner-Str. ',
'Georg-Heck-Weg ',
'Georg-Speyer-Str. ',
'Georg-Treser-Str. ',
'Georg-Voigt-Str. ',
'Georg-Wolff-Str. ',
'Gepiden-Forum ',
'Geranienweg ',
'Gerauer Str. ',
'Gerbermühlstr. ',
'Gerhard-Domagk-Str. ',
'Gerhardsrainweg ',
'Gerhart-Hauptmann-Ring ',
'Gerichtsstr. ',
'Gerlachstr. ',
'Germaniaplatz ',
'Germaniastr. ',
'Germaniastr. ',
'Gerningstr. ',
'Gerolsteiner Str. ',
'Gersthofer Str. ',
'Gerstweg ',
'Gervinusstr. ',
'Geschwister-Scholl-Str. ',
'Gickelgasse ',
'Gießener Str. ',
'Gießfeldstr. ',
'Gilbrechtstr. ',
'Ginnheimer Hohl ',
'Ginnheimer Landstr. ',
'Ginnheimer Mühlgasse ',
'Ginnheimer Stadtweg ',
'Ginnheimer Stadtweg ',
'Ginnheimer Str. ',
'Ginnheimer Waldgasse ',
'Ginsterweg ',
'Gisele-Freund-Platz ',
'Gladenbacher Weg ',
'Gladiolenstr. ',
'Gläsern Gäßchen ',
'Glaserstr. ',
'Glashüttener Str. ',
'Glaskopfweg ',
'Glauburgstr. ',
'Gleimstr. ',
'Glockenblumenweg ',
'Glockengasse ',
'Glogauer Str. ',
'Gluckstr. ',
'Goetheplatz ',
'Goetheschneise ',
'Goethestr. ',
'Goetzstr. ',
'Goldammerstr. ',
'Goldbergweg ',
'Goldfedergasse ',
'Goldgewann ',
'Goldgrubenstr. ',
'Goldhutgasse ',
'Goldpeppingstr. ',
'Goldregenstr. ',
'Goldsteinschneise ',
'Goldsteinschneise ',
'Goldsteinstr. ',
'Golfstr. ',
'Golfstr. ',
'Golub-Lebedenko-Platz ',
'Gontardstr. ',
'Gonzenheimer Str. ',
'Görlitzer Str. ',
'Görresstr. ',
'Gotenstr. ',
'Gottfried-Keller-Str. ',
'Graebestr. ',
'Graf-Vollrath-Weg ',
'Graf-von-Stauffenberg-Allee ',
'Gräfendeichstr. ',
'Grafenstr. ',
'Gräfin-Dönhoff-Str. ',
'Gräfstr. ',
'Gräfstr. ',
'Gräsigter Weg ',
'Grasmückenweg ',
'Grastränkschneise ',
'Grauer Stein ',
'Gravensteiner-Platz ',
'Grazer Weg ',
'Gref-Völsing-Str. ',
'Greifstr. ',
'Greifswalder Weg ',
'Grempstr. ',
'Grenzschneise ',
'Grenzschneise ',
'Gretapfelstr. ',
'Grethenweg ',
'Griesheimer Fußweg ',
'Griesheimer Fußweg ',
'Griesheimer Stadtweg ',
'Griesheimer Ufer ',
'Griesheimerweg ',
'Grillscher Weg ',
'Grillparzerstr. ',
'Grimoldweg ',
'Grommetstr. ',
'Gronauer Str. ',
'Große Bockenheimer Str. ',
'Große Eschenheimer Str. ',
'Große Fischerstr. ',
'Große Friedberger Str. ',
'Große Gallusstr. ',
'Große Gallusstr. ',
'Große Nelkenstr. ',
'Große Rittergasse ',
'Große Seestr. ',
'Große Spillingsgasse ',
'Großer Hasenpfad ',
'Großer Hirschgraben ',
'Großer Ruppenackerweg ',
'Grotefendstr. ',
'Grubweg ',
'Gruftenweg ',
'Gründenseestr. ',
'Grundweg ',
'Grundwiesenstr. ',
'Grüne Str. ',
'Grüne Weide ',
'Grüne Winkel ',
'Grüneburgplatz ',
'Grüneburgweg ',
'Grüneburgweg ',
'Gruneliusstr. ',
'Grusonstr. ',
'Guaitastr. ',
'Guerickestr. ',
'Guiollettstr. ',
'Gummersbergstr. ',
'Gundelandstr. ',
'Günderrodestr. ',
'Gundhofstr. ',
'Günter-Vogt-Ring ',
'Günther-Groenhoff-Str. ',
'Günthersburgallee ',
'Güntherstr. ',
'Gustav-Behringer-Str. ',
'Gustav-Freytag-Str. ',
'Gustav-Mahler-Str. ',
'Gustavsallee ',
'Gustavsburgstr. ',
'Gutenbergstr. ',
'Güterplatz ',
'Gutleuthofweg ',
'Gutleutstr. ',
'Gutleutstr. ',
'Gutzkowstr. ',
'Gwinnerstr. ',
'H.-P.-Müller-Platz ',
'Haardtwaldplatz ',
'Haardtwaldstr. ',
'Habelstr. ',
'Habichtschneise ',
'Habichtsweg ',
'Habsburgerallee ',
'Hachenburger Str. ',
'Hadamarer Str. ',
'Hadrianstr. ',
'Haeberlinstr. ',
'Haenischstr. ',
'Haeuserhofweg ',
'Haeussermannstr. ',
'Hafenmühlenweg ',
'Hafenstr. ',
'Hafentunnel ',
'Haferackerschneise ',
'Hafnerstr. ',
'Hagebuttenweg ',
'Hagenstr. ',
'Hahnbergweg ',
'Hahnenkammstr. ',
'Hahnstr. ',
'Haigerer Str. ',
'Hainbuchenschneise ',
'Hainbuchenstr. ',
'Hainer Hof ',
'Hainer Weg ',
'Hainerbrückweg ',
'Haingasse ',
'Haingrabenstr. ',
'Haintalstr. ',
'Hakengasse ',
'Hallgartenstr. ',
'Halmstr. ',
'Hamburger Allee ',
'Hammanstr. ',
'Hammarskjöldring ',
'Hammelsgasse ',
'Hammersbacher Weg ',
'Hanauer Landstr. ',
'Hanauer Landstr. ',
'Händelstr. ',
'Hänggasse ',
'Hannah-Arendt-Str. ',
'Hans-Bethe-Str. ',
'Hans-Böckler-Str. ',
'Hans-Eick-Weg ',
'Hans-Herkommer-Ring ',
'Hans-Herkommer-Ring ',
'Hans-Kobald-Weg ',
'Hans-Leistikow-Str. ',
'Hans-Loskant-Weg ',
'Hans-Pfitzner-Str. ',
'Hans-Poelzig-Str. ',
'Hans-Sachs-Str. ',
'Hans-Thoma-Str. ',
'Hansaallee ',
'Hansaallee ',
'Hansenweg ',
'Hansteinstr. ',
'Hardenbergstr. ',
'Harheimer Stadtweg ',
'Harheimer Weg ',
'Harkortstr. ',
'Harry-Fuld-Str. ',
'Harthweg ',
'Hartmann-Ibach-Str. ',
'Hartmannsweilerstr. ',
'Hartmannweg ',
'Haselnußpfad ',
'Hasengasse ',
'Hasselhorstweg ',
'Hattersheimer Str. ',
'Hattsteiner Str. ',
'Hauer-Mauer-Weg ',
'Hauptwache B-Ebene ',
'Hauptwache-Passage ',
'Hausener Brückweg ',
'Hausener Obergasse ',
'Hausener Weg ',
'Häuser Gasse ',
'Hebelstr. ',
'Hebelstr. ',
'Heckenrosenweg ',
'Heckerstr. ',
'Hedderichstr. ',
'Heddernheimer Kirchstr. ',
'Heddernheimer Landstr. ',
'Heddernheimer Steg ',
'Hedwig-Dransfeld-Str. ',
'Heerstr. ',
'Hegarstr. ',
'Hegelstr. ',
'Heidelbachstr. ',
'Heidelberger Str. ',
'Heidenstockschneise ',
'Heideplatz ',
'Heidestr. ',
'Heidestr. ',
'Heidetränkstr. ',
'Heigenbrücker Weg ',
'Heilbronner Str. ',
'Heiligenstock ',
'Heiligenstockweg ',
'Heiligenstockweg ',
'Heiligkreuzgasse ',
'Heilmannstr. ',
'Heilsberger Str. ',
'Heimatring ',
'Heimchenweg ',
'Heinestr. ',
'Heinrich-Baldes-Str. ',
'Heinrich-Becker-Str. ',
'Heinrich-Berbalk-Str. ',
'Heinrich-Bingemer-Weg ',
'Heinrich-Bleicher-Str. ',
'Heinrich-Hardt-Str. ',
'Heinrich-Hertz-Str. ',
'Heinrich-Hoffmann-Str. ',
'Heinrich-Hopf-Str. ',
'Heinrich-Kegelmann-Weg ',
'Heinrich-Lanz-Allee ',
'Heinrich-Limpert-Weg ',
'Heinrich-Lübke-Str. ',
'Heinrich-Plett-Str. ',
'Heinrich-Rößler-Str. ',
'Heinrich-Seliger-Str. ',
'Heinrich-Stahl-Str. ',
'Heinrich-Tessenow-Weg ',
'Heinrich-Wilhelm-Römer-Anlage ',
'Heinrich-Zinß-Weg ',
'Heinrichstr. ',
'Heinz-Herbert-Karry-Str. ',
'Heinz-Saalig-Weg ',
'Heinzstr. ',
'Heisterstr. ',
'Heldenbergener Str. ',
'Helene-Adler-Weg ',
'Helene-Lange-Str. ',
'Hellerhofstr. ',
'Helmholtzstr. ',
'Helmut-Coing-Weg ',
'Helmut-Sittler-Promenade ',
'Helmut-Walcha-Str. ',
'Hennegasse ',
'Henning-Von-Tresckow-Str. ',
'Henriette-Fürth-Str. ',
'Henry-Budge-Str. ',
'Henschelstr. ',
'Henselstr. ',
'Henselweg ',
'Herbartstr. ',
'Herbert-Boehm-Str. ',
'Herbert-von-Meister-Str. ',
'Herbesthaler Str. ',
'Herborner Str. ',
'Herchenhainer Weg ',
'Herderstr. ',
'Hermann-Brill-Str. ',
'Hermann-Eggert-Str. ',
'Hermann-Eggert-Str. ',
'Hermann-Küster-Str. ',
'Hermann-Mäckler-Ring ',
'Hermann-Waibel-Allee ',
'Hermann-Wendel-Str. ',
'Hermannspforte ',
'Hermannstr. ',
'Hermesweg ',
'Herrenapfelstr. ',
'Herrenwäldchen ',
'Herriotstr. ',
'Herrnstr. ',
'Hersfelder Str. ',
'Herweghstr. ',
'Herxheimerstr. ',
'Herzbergstr. ',
'Herzogstr. ',
'Hesselbergweg ',
'Hessenplatz ',
'Hessestr. ',
'Heugasse ',
'Heuschneise ',
'Heusingerstr. ',
'Heussenstammstr. ',
'Heussleinstr. ',
'Heylstr. ',
'Hibiskusstr. ',
'Hildburghäuser Weg ',
'Hildegard-Schaeder-Str. ',
'Hildegard-von-Bingen-Weg ',
'Hilligengasse ',
'Hinkelsteinschneise ',
'Hinkelsteinschneise ',
'Hinter Dem Lämmchen ',
'Hinter dem Sausee ',
'Hinter den Eichbäumen ',
'Hinter den Obergärten ',
'Hinter den Ulmen ',
'Hinter der Burg ',
'Hinter Der Eckenheimer Mauer ',
'Hinter Der Krebsmühle ',
'Hinter der Schönen Aussicht ',
'Hintergasse ',
'Hinterm Bachberg ',
'Hinterm Hain ',
'Hirschhornstr. ',
'Hirtenstr. ',
'Hirzenhainer Str. ',
'Hochfeldstr. ',
'Hochmuhl ',
'Hochschildstr. ',
'Hochstädter Str. ',
'Höchster Bahnstr. ',
'Höchster Markt ',
'Höchster Schloßplatz ',
'Höchster Weg ',
'Hochstr. ',
'Hoechster-Farben-Str. ',
'Hofeckweg ',
'Hoffeldstr. ',
'Hofgartenweg ',
'Hofhausstr. ',
'Hofhausstr. ',
'Hofheimer Str. ',
'Hofstr. ',
'Hohe Brück ',
'Hohe Kanzel ',
'Hohe Stätte ',
'Hohe Str. ',
'Hohemarkstr. ',
'Höhenblick ',
'Hohenstaufenstr. ',
'Hohensteiner Str. ',
'Höhenstr. ',
'Hoherodskopfstr. ',
'Holbeinsteg ',
'Holbeinstr. ',
'Hölderlinstr. ',
'Höllbergstr. ',
'Höllenweg ',
'Hollerkopfstr. ',
'Höllgasse ',
'Holunderweg ',
'Holzgraben ',
'Holzhausenstr. ',
'Holzhecke ',
'Holzlachstr. ',
'Holzweg ',
'Holzweg ',
'Holzweg ',
'Homburger Hohl ',
'Homburger Landstr. ',
'Homburger Landstr. ',
'Homburger Landstr. ',
'Homburger Str. ',
'Homolkaweg ',
'Honsellbrücke ',
'Honsellstr. ',
'Horles ',
'Hornauer Str. ',
'Hörselbergstr. ',
'Horst-Schulmann-Str. ',
'Hortensienring ',
'Hospitalstr. ',
'Hostatostr. ',
'Howaldtstr. ',
'Hubertusgasse ',
'Hufnagelstr. ',
'Hügelschneise ',
'Hügelstr. ',
'Hügelstr. ',
'Hugo-Eckener-Ring ',
'Hugo-Junkers-Str. ',
'Hugo-Kallenbach-Str. ',
'Hugo-Sinzheimer-Str. ',
'Hugo-Stinnes-Str. ',
'Hugo-Wolf-Str. ',
'Hühnermarkt ',
'Hühnerweg ',
'Hullach ',
'Hülya-Platz ',
'Humboldtstr. ',
'Humbrachtstr. ',
'Humperdinckstr. ',
'Humserstr. ',
'Hünfelder Str. ',
'Hungener Str. ',
'Hunsrückstr. ',
'Huswertstr. ',
'Huthmacherstr. ',
'Huthpark ',
'Hynspergstr. ',
'Ibellstr. ',
'Idarwaldstr. ',
'Idsteiner Str. ',
'Ignatz-Bubis-Brücke ',
'Ilbenstädter Str. ',
'Ilkenhansstr. ',
'Ilse-Bing-Str. ',
'Iltispfad ',
'Im Bärengarten ',
'Im Bleichgarten ',
'Im Brandsee ',
'Im Braungeröll ',
'Im Brombeerfeld ',
'Im Bruch ',
'Im Burgfeld ',
'Im Dinkelfeld ',
'Im Dörner ',
'Im Eichwäldchen ',
'Im Enkheimer Weimerhaus ',
'Im Feldchen ',
'Im Fuchsloch ',
'Im Füldchen ',
'Im Galluspark ',
'Im Geeren ',
'Im Geiersrain ',
'Im Grund ',
'Im Hain ',
'Im Hauptbahnhof ',
'Im Heidenfeld ',
'Im Heimgarten ',
'Im Heisenrath ',
'Im Hermeshain ',
'Im Herzen Von Europa ',
'Im Hilgenfeld ',
'Im Hirschländchen ',
'Im Hofheimer Grund ',
'Im Kalk ',
'Im Kammerdorf ',
'Im Kirschenstück ',
'Im Kirschenwäldchen ',
'Im Klausenstück ',
'Im Klausenstück ',
'Im Klingenfeld ',
'Im Kreuzegut ',
'Im Mainfeld ',
'Im Mellsig ',
'Im Mittleren Sand ',
'Im Nardholz ',
'Im Niederfeld ',
'Im Nizza ',
'Im Prüfling ',
'Im Rosenträger ',
'Im Sachsenlager ',
'Im Sauern ',
'Im Sechholder ',
'Im Sperber ',
'Im Staffel ',
'Im Steinbügel ',
'Im Steinchen ',
'Im Storchenhain ',
'Im Teller ',
'Im Tiefen Weg ',
'Im Triborn ',
'Im Trieb ',
'Im Trierischen Hof ',
'Im Trutz Frankfurt ',
'Im Uhrig ',
'Im Vogelsgesang ',
'Im Waldfeld ',
'Im Weidenfeld ',
'Im Weidensee ',
'Im Weimel ',
'Im Wickengarten ',
'Im Wiesengarten ',
'Im Wiesengrund ',
'Im Winkel ',
'Im Wörth ',
'Im Ziegelfeld ',
'Imkerweg ',
'Immermannstr. ',
'in Den Aspen ',
'In den Biegen ',
'in Den Gräben ',
'In den Grummetwiesen ',
'In den Schafgärten ',
'In den Seewiesen ',
'In den Stegwiesen ',
'in Den Teichen ',
'In den Waldgärten ',
'In den Zeuläckern ',
'In der Au ',
'In der Beginenklause ',
'in Der Erle ',
'in Der Fuchskaut ',
'in Der Kätcheslach ',
'In der Kron ',
'In der Krümm ',
'In Der Römerstadt ',
'In der Rosengewann ',
'In der Roterde ',
'in Der Sauren Wiese ',
'In der Schildwacht ',
'In der Wink ',
'Inckusstr. ',
'Ingelheimer Str. ',
'Ingolstädter Str. ',
'Inheidener Str. ',
'Inselgäßchen ',
'Inselsbergstr. ',
'Insterburger Str. ',
'Interessentenweg ',
'Intzestr. ',
'Iselinstr. ',
'Isenburger Schneise ',
'Isenburgstr. ',
'Jacob-Schiff-Str. ',
'Jacobiweg ',
'Jacobiweiher ',
'Jacobystr. ',
'Jadegürtelbrücke ',
'Jagdhüttenschneise ',
'Jägerallee ',
'Jägersteg ',
'Jahnstr. ',
'Jakob-Carl-Junior-Str. ',
'Jakob-Heller-Str. ',
'Jakob-Latscha-Str. ',
'Jakob-Leisler-Str. ',
'Jakob-Quirin-Weg ',
'Jakobsbrunnenstr. ',
'Jasminweg ',
'Jaspertstr. ',
'Jean-Albert-Schwarz-Str. ',
'Jean-Gardner-Batten-Str. ',
'Jean-Kempf-Weg ',
'Jean-Monnet-Str. ',
'Jean-Paul-Str. ',
'Jenaer Weg ',
'Jenny-Apolant-Weg ',
'Joachim-Becher-Str. ',
'Joachim-Biermann-Str. ',
'Johann-Beyer-Weg ',
'Johann-Georg-Elser-Str. ',
'Johann-Georg-Fahr-Anlage ',
'Johann-Klohmann-Str. ',
'Johann-Klotz-Str. ',
'Johann-Sittig-Str. ',
'Johann-Usener-Str. ',
'Johanna-Kirchner-Str. ',
'Johanna-Melber-Weg ',
'Johanna-Spyri-Weg ',
'Johanna-Tesch-Platz ',
'Johannes-Lamp-Str. ',
'Johannesallee ',
'Jordanstr. ',
'Josbacher Str. ',
'Josef-Bautz-Str. ',
'Josef-Benner-Weg ',
'Josef-Dey-Weg ',
'Josef-Eicher-Str. ',
'Josef-Fenzl-Str. ',
'Josef-May-Str. ',
'Josef-Wirmer-Str. ',
'Joseph-Von-Fraunhofer-Str. ',
'Josephskirchstr. ',
'Juchostr. ',
'Jügelstr. ',
'Jugenheimer Str. ',
'Julius-Brecht-Str. ',
'Julius-Heyman-Str. ',
'Julius-Leber-Weg ',
'Julius-Munk-Anlage ',
'Juliusstr. ',
'Junghofstr. ',
'Jungmannstr. ',
'Jungstr. ',
'Jürgen-Ponto-Platz ',
'Justinianstr. ',
'Justinuskirchhof ',
'Justinuskirchstr. ',
'Justinusplatz ',
'Kahnplatz ',
'Kaiser-Sigmund-Str. ',
'Kaiserbahnweg ',
'Kaisergässchen ',
'Kaiserhofstr. ',
'Kaiserkronenweg ',
'Kaiserpassage ',
'Kaiserplattschneise ',
'Kaiserplatz ',
'Kaiserstr. ',
'Kaiserstr. ',
'Kaisertannenweg ',
'Kalbächer Gasse ',
'Kalbacher Hauptstr. ',
'Kalbacher Niddapfad ',
'Kalbacher Stadtpfad ',
'Kalkentalstr. ',
'Kallestr. ',
'Kalmitstr. ',
'Kaltmühle ',
'Kaltmühlstr. ',
'Kamelienstr. ',
'Kameruner Rosengärtchen ',
'Kandelstr. ',
'Kannengießergasse ',
'Kantapfelstr. ',
'Kantstr. ',
'Kapersburgstr. ',
'Kapitän-Lehmann-Str. ',
'Kappusstr. ',
'Karbener Str. ',
'Karl-Albert-Str. ',
'Karl-Bieber-Höhe ',
'Karl-Blum-Allee ',
'Karl-Flesch-Str. ',
'Karl-Gerold-Platz ',
'Karl-Kautsky-Weg ',
'Karl-Klee-Weg ',
'Karl-König-Weg ',
'Karl-Kotzenberg-Str. ',
'Karl-Lachmann-Str. ',
'Karl-Marx-Str. ',
'Karl-Pfeuffer-Str. ',
'Karl-Ritscher-Anlage ',
'Karl-Scheele-Str. ',
'Karl-Schüler-Weg ',
'Karl-Stieler-Str. ',
'Karl-von-Drais-Str. ',
'Karl-Wessendorft-Str. ',
'Karlsbader Str. ',
'Karlsruher Str. ',
'Karlstr. ',
'Karmelitergasse ',
'Karolingerweg ',
'Karpfengasse ',
'Karpfenweg ',
'Kasernenstr. ',
'Kasinostr. ',
'Kasseler Str. ',
'Kastanienallee ',
'Kastanienallee ',
'Kastanienschneise ',
'Kastanienschneise ',
'Kastanienstr. ',
'Kastellstr. ',
'Kätcheslachweg ',
'Katharina-Petri-Str. ',
'Katharina-Staritz-Str. ',
'Katharinenkreisel ',
'Katharinenpforte ',
'Käthchen-Paulus-Str. ',
'Käthe-Kruse-Str. ',
'Katherine-Stinson-Weg ',
'Kattergasse ',
'Kattowitzer Str. ',
'Katzenpforte ',
'Katzenstirn ',
'Kauber Weg ',
'Kaufunger Str. ',
'Kaulbachstr. ',
'Kaulbachstr. ',
'Kautenhof ',
'Kegelbahn ',
'Kehreinstr. ',
'Kelkheimer Str. ',
'Kellerbornstr. ',
'Kellerskopfweg ',
'Kellertunnel Terminal  ',
'Kelsterbacher Schneise ',
'Kelsterbacher Str. ',
'Kelsterbacher Weg ',
'Keltenstr. ',
'Kennedyallee ',
'Kennedyallee ',
'Keplerstr. ',
'Keßlerstr. ',
'Kesselbruchschneise ',
'Kesselstädter Str. ',
'Kettelerallee ',
'Kettenhofweg ',
'Kiebitzpfad ',
'Kiefernstr. ',
'Kiesbergweg ',
'Kiesschneise ',
'Kiesstr. ',
'Kilianstädter Str. ',
'Kinkelstr. ',
'Kinzigstr. ',
'Kirchbergweg ',
'Kirchgartenstr. ',
'Kirchgasse ',
'Kirchhainer Str. ',
'Kirchhofsweg ',
'Kirchnerstr. ',
'Kirchpfad ',
'Kirchplatz ',
'Kirchschneise ',
'Kirschalenschneise ',
'Kirschbaumweg ',
'Kirschenallee ',
'Kirschwaldstr. ',
'Klapperfeldstr. ',
'Klappergasse ',
'Klarastr. ',
'Klauerstr. ',
'Klaus-Groth-Str. ',
'Kleebergstr. ',
'Kleemannstr. ',
'Kleestr. ',
'Kleine Bockenheimer Str. ',
'Kleine Brückenstr. ',
'Kleine Fischergasse ',
'Kleine Friedberger Str. ',
'Kleine Hochstr. ',
'Kleine Höllbergstr. ',
'Kleine Nelkenstr. ',
'Kleine Rittergasse ',
'Kleine Schüttgrabenstr. ',
'Kleine Seestr. ',
'Kleine Spillingsgasse ',
'Kleine Wiesenau ',
'Kleiner Hirschgraben ',
'Kleiner Ruppenackerweg ',
'Kleingartenweg ',
'Kleinmarkthalle ',
'Kleinschmidtstr. ',
'Kleinwiesenschneise ',
'Kleiststr. ',
'Klepperschneise ',
'Klettenbergstr. ',
'Kleyerstr. ',
'Klimsch-Anlage ',
'Klingenberger Str. ',
'Klingenweg ',
'Klingenweg ',
'Klingerstr. ',
'Klitscherstr. ',
'Klosterhofstr. ',
'Klüberstr. ',
'Kneiselsmühle ',
'Kniebisstr. ',
'Knorrstr. ',
'Knöterichweg ',
'Kobbachstr. ',
'Koblenzer Str. ',
'Kochstr. ',
'Kohlbrandstr. ',
'Kohlrauschweg ',
'Kolbenbergstr. ',
'Kolberger Weg ',
'Kollwitzstr. ',
'Kölner Str. ',
'Kolpingstr. ',
'Komturstr. ',
'Königsberger Str. ',
'Königsbrunnenweg ',
'Königslacher Str. ',
'Königsteiner Str. ',
'Königswarterstr. ',
'Königswiesenweg ',
'Konrad-Adenauer-Str. ',
'Konrad-Broßwitz-Str. ',
'Konrad-Duden-Weg ',
'Konrad-Glatt-Str. ',
'Konrad-Hoenen-Weg ',
'Konrad-Meyer-Weg ',
'Konrad-Zuse-Str. ',
'Konstabler Arkaden ',
'Konstablerwache ',
'Konstablerwache B-Ebene ',
'Konstantinstr. ',
'Konstanzer Str. ',
'Kopenhagener Str. ',
'Kopernikusstr. ',
'Köpperner Str. ',
'Körberstr. ',
'Korffstr. ',
'Körnerstr. ',
'Kornmarkt ',
'Korsoweg ',
'Koselstr. ',
'Kostheimer Str. ',
'Kracauerstr. ',
'Krälingweg ',
'Kranengasse ',
'Kranentrank ',
'Kranichsteiner Str. ',
'Kransberger Weg ',
'Krautgartenweg ',
'Kreutzerstr. ',
'Kreuzbergstr. ',
'Kreuzerhohl ',
'Kreuzerweg ',
'Kreuznacher Str. ',
'Kreuzstr. ',
'Kreuzweg ',
'Kriegkstr. ',
'Krifteler Str. ',
'Krögerstr. ',
'Kronberger Str. ',
'Kronengasse ',
'Kronthaler Str. ',
'Kruggasse ',
'Krummauer Str. ',
'Krumme Weiden ',
'Krumme-Loog-Schneise ',
'Krümmling ',
'Kruppstr. ',
'Küferstr. ',
'Kuhdamm ',
'Kühhornshofweg ',
'Kuhpfadschneise ',
'Kuhwaldstr. ',
'Kullmannstr. ',
'Kupferhammer ',
'Kurfürstenplatz ',
'Kurfürstenstr. ',
'Kurhessenstr. ',
'Kurmainzer Str. ',
'Kurmainzer Str. ',
'Kurmarkstr. ',
'Kurt-Blaum-Str. ',
'Kurt-Halbritter-Anlage ',
'Kurt-Schumacher-Str. ',
'Kurzgasse ',
'Kurzröderstr. ',
'Kutscherweg ',
'L  ',
'Lachegraben ',
'Lachnerstr. ',
'Lachweg ',
'Ladenburgstr. ',
'Ladestr. ',
'Lagwiesenweg ',
'Lahmeyerbrücke ',
'Lahmeyerstr. ',
'Lahnstr. ',
'Lamboystr. ',
'Landauer Str. ',
'Länderweg ',
'Landgraben ',
'Landgraf-Philipp-Str. ',
'Landgraf-Wilhelm-Str. ',
'Landgrafenstr. ',
'Landvogtstr. ',
'Lange Baum Schneise ',
'Lange Meile ',
'Lange Schirn ',
'Lange Str. ',
'Langebaumgrundschneise ',
'Langenhainer Str. ',
'Langenselbolder Str. ',
'Langer Weg ',
'Langheckenweg ',
'Langobardenweg ',
'Langschneise ',
'Langweidenstr. ',
'Lappengasse ',
'Lärchenschneise ',
'Lärchenstr. ',
'Lassallestr. ',
'Laubestr. ',
'Launhardtstr. ',
'Launitzstr. ',
'Laurentiusstr. ',
'Lausitzstr. ',
'Lauterbacher Str. ',
'Lavendelweg ',
'Lebensbaumweg ',
'Leberecht-Migge-Anlage ',
'Leerbachstr. ',
'Legienstr. ',
'Lehmkautstr. ',
'Lehrbergerstr. ',
'Leibbrandstr. ',
'Leibnizstr. ',
'Leimenrode ',
'Leinpfad ',
'Leinwebergasse ',
'Leipziger Str. ',
'Leipziger Str. ',
'Lenaustr. ',
'Lenzenbergstr. ',
'Leo-Gans-Str. ',
'Leo-Tolstoj-Str. ',
'Leonardo-Da-Vinci-Allee ',
'Leonhard-Heißwolf-Str. ',
'Leonhardsgasse ',
'Leonhardskirchhof ',
'Leopold-Ehrmann-Str. ',
'Lepsiusstr. ',
'Lerchesbergring ',
'Lerchesbergweg ',
'Lersnerstr. ',
'Lessingstr. ',
'Lettigkautweg ',
'Letzter Hasenpfad ',
'Leuchte ',
'Leunabrücke ',
'Leunastr. ',
'Leunastr. ',
'Leutholdstr. ',
'Leverkuser Str. ',
'Lia-Wöhr-Str. ',
'Libellenweg ',
'Licher Str. ',
'Lichnowskyplatz ',
'Lichtenbergstr. ',
'Lichtensteinstr. ',
'Lichtetalschneise ',
'Liebfrauenberg ',
'Liebfrauenstr. ',
'Liebigstr. ',
'Liebknechtstr. ',
'Liederbacher Str. ',
'Lieferantenzufahrt ',
'Liefersteinschneise ',
'Liegnitzer Str. ',
'Liesel-Christ-Anlage ',
'Ligusterweg ',
'Lili-Schönemann-Steige ',
'Liliencronstr. ',
'Lilienthalallee ',
'Lilo-Günzler-Str. ',
'Limescorso ',
'Limpurgergasse ',
'Lindberghplatz ',
'Lindenallee ',
'Lindenau ',
'Lindenbaum ',
'Lindenhag ',
'Lindenhof ',
'Lindenring ',
'Lindenscheidstr. ',
'Lindenstr. ',
'Lindleystr. ',
'Linkstr. ',
'Linnéstr. ',
'Lise-Meitner-Str. ',
'Lissabonner Str. ',
'Listweg ',
'Lixfelder Weg ',
'Lochmühlstr. ',
'Loenstr. ',
'Loensweg ',
'Löherstr. ',
'Löhnunggasse ',
'Lohoffstr. ',
'Lohrgasse ',
'Lokalbahnhof ',
'Londoner Str. ',
'Lönsschneise ',
'Lönsweg ',
'Loreleistr. ',
'Lorsbacher Str. ',
'Lorscher Str. ',
'Lortzingstr. ',
'Lötzener Str. ',
'Lotzstr. ',
'Louis-Appia-Passage ',
'Louis-Pasteur-Str. ',
'Louisaschneise ',
'Löwengasse ',
'Lübecker Str. ',
'Lucaestr. ',
'Luciusstr. ',
'Lucy-Hillebrand-Str. ',
'Ludolfusstr. ',
'Ludwig-Emmel-Weg ',
'Ludwig-Erhard-Anlage ',
'Ludwig-Erhard-Anlage ',
'Ludwig-Fulda-Weg ',
'Ludwig-Gallmeyer-Str. ',
'Ludwig-Gehm-Weg ',
'Ludwig-Hensler-Str. ',
'Ludwig-Jost-Allee ',
'Ludwig-Klemann-Weg ',
'Ludwig-Landmann-Str. ',
'Ludwig-Quidde-Str. ',
'Ludwig-Rehn-Str. ',
'Ludwig-Reinheimer-Str. ',
'Ludwig-Richter-Str. ',
'Ludwig-Ruppel-Str. ',
'Ludwig-Scriba-Str. ',
'Ludwig-Tieck-Str. ',
'Ludwig-Zamenhof-Weg ',
'Ludwigsburger Weg ',
'Ludwigshafener Str. ',
'Ludwigstr. ',
'Ludwigstr. ',
'Luginsland ',
'Luisenplatz ',
'Luisenstr. ',
'Lupinenweg ',
'Lurgiallee ',
'Luthmerstr. ',
'Luxemburgerallee ',
'Luzernenweg ',
'Lyoner Str. ',
'Maastrichter Ring ',
'Madrider Str. ',
'Magda-Spiegel-Weg ',
'Magnolienstr. ',
'Mahräckerstr. ',
'Mailänder Str. ',
'Mainberg ',
'Mainfeldstr. ',
'Mainkai ',
'Mainkurstr. ',
'Mainluststr. ',
'Mainstr. ',
'Maintaler Grenzschneise ',
'Maintor ',
'Mainwasenweg ',
'Mainwasenweg ',
'Mainzer Bahnweg ',
'Mainzer Bahnweg ',
'Mainzer Landstr. ',
'Mainzer Landstr. ',
'Mainzer Landstr. ',
'Malapertstr. ',
'Malßstr. ',
'Malvenweg ',
'Mammolshainer Str. ',
'Manderscheider Str. ',
'Mannheimer Str. ',
'Mannheimer Str. ',
'Manskopfstr. ',
'Marbachweg ',
'Marbachweg ',
'Marburger Str. ',
'Marderweg ',
'Margarete-Steiff-Str. ',
'Margarete-Susman-Weg ',
'Margaretenstr. ',
'Margeritenweg ',
'Marianne-Beuchert-Platz ',
'Mariannenstr. ',
'Marie-Curie-Str. ',
'Marie-Luise-Kaschnitz-Str. ',
'Marienberger Str. ',
'Marienburgstr. ',
'Marienstr. ',
'Mark-Aurel-Str. ',
'Märker Str. ',
'Markgrafenstr. ',
'Markomannenweg ',
'Markt ',
'Marktstr. ',
'Marquardstr. ',
'Marschnerstr. ',
'Mart-Stam-Str. ',
'Martin Henrich Anlage ',
'Martin-Böff-Gasse ',
'Martin-Elsässer-Weg ',
'Martin-Luther-Platz ',
'Martin-Luther-Str. ',
'Martin-Luther-Str. ',
'Martin-May-Str. ',
'Martin-Niemöller-Str. ',
'Martin-Schäfer-Weg ',
'Martin-Zahn-Str. ',
'Martinskirchstr. ',
'Martinsweg ',
'Martorffstr. ',
'Marxheimer Platz ',
'Marxheimer Str. ',
'Maßbornstr. ',
'Maßholderpfad ',
'Massenheimer Str. ',
'Mathildenplatz ',
'Mathildenstr. ',
'Matisseweg ',
'Matternstr. ',
'Matthias-Claudius-Str. ',
'Mattiakerweg ',
'Mauerweg ',
'Maulbeerstr. ',
'Maunzenweiherschneise ',
'Mauritiusstr. ',
'Max-Beckmann-Str. ',
'Max-Bock-Str. ',
'Max-Born-Str. ',
'Max-Bromme-Steig ',
'Max-Bromme-Steig ',
'Max-Eyth-Str. ',
'Max-Hartig-Weg ',
'Max-Hirsch-Str. ',
'Max-Holder-Str. ',
'Max-Horkheimer-Str. ',
'Max-Kirschner-Weg ',
'Max-Planck-Str. ',
'Max-Pruss-Str. ',
'Max-Quarck-Str. ',
'Max-Reger-Str. ',
'Max-von-Laue-Str. ',
'Max-Von-Pettenkofer-Weg ',
'Maximilianstr. ',
'Maybachbrücke ',
'Maybachstr. ',
'Mayfarthstr. ',
'Mechtildstr. ',
'Mecklenburger Str. ',
'Meerholzer Str. ',
'Meersburger Str. ',
'Meier-Seligmann-Weg ',
'Meininger Weg ',
'Meisengasse ',
'Melchiorstr. ',
'Melemstr. ',
'Melibocusstr. ',
'Melli-Beese-Str. ',
'Melsunger Str. ',
'Mendelssohnstr. ',
'Mendelssohnweg ',
'Mercatorstr. ',
'Mergenthalerstr. ',
'Merianplatz ',
'Merianstr. ',
'Mertonpassage ',
'Mertonstr. ',
'Merzenstr. ',
'Merziger Weg ',
'Messelweg ',
'Metzlerstr. ',
'Metzstr. ',
'Michael-Stumpf-Str. ',
'Michaelstr. ',
'Mierendorffstr. ',
'Milanschneise ',
'Milseburgstr. ',
'Miltenberger Str. ',
'Miquelallee ',
'Miquelallee ',
'Miquelallee ',
'Miquelsweg ',
'Mithrasstr. ',
'Mittelseestr. ',
'Mittelweg ',
'Mittelweg ',
'Mittelweg ',
'Mittelweg ',
'Mittlerer Hasenpfad ',
'Mittlerer Schafhofweg ',
'Mockstädter Str. ',
'Mombacher Weg ',
'Mönchhofstr. ',
'Monchstr. ',
'Monetweg ',
'Monisstr. ',
'Montabaurer Str. ',
'Montgolfier-Allee ',
'Mörderbrunnenschneise ',
'Mörfelder Landstr. ',
'Mörfelder Schneise ',
'Morgensternstr. ',
'Morgenzeile ',
'Mörikestr. ',
'Morsestr. ',
'Moselstr. ',
'Motzstr. ',
'Mouson-Brücke ',
'Mousonstr. ',
'Muckermannstr. ',
'Mühlackerstr. ',
'Mühlbruchstr. ',
'Mühlgasse ',
'Mühlheimer Str. ',
'Mühlschneise ',
'Mühlweg ',
'Mühlwehrstr. ',
'Mühlwiesenstr. ',
'Mulanskystr. ',
'Müllerstr. ',
'Mümlingstr. ',
'Mumm-von-Schwarzenstein-Str. ',
'Münchener Str. ',
'Münsterer Str. ',
'Münsterer Weg ',
'Münzenberger Str. ',
'Münzgasse ',
'Musikantenweg ',
'Muthesiusweg ',
'Myliusstr. ',
'Nach dem Brand ',
'Nachtigallenweg ',
'Nachtigallenweg ',
'Nahestr. ',
'Nansenring ',
'Narzissenstr. ',
'Nassauer Str. ',
'Nathan-Trier-Str. ',
'Nauheimer Str. ',
'Nebeniusstr. ',
'Neckarstr. ',
'Nedergäßchen ',
'Neebstr. ',
'Nell-Breuning-Str. ',
'Nesenstr. ',
'Nesselbuschstr. ',
'Neu-Zeilsheim ',
'Neue Börsenstr. ',
'Neue Fahrt ',
'Neue Kräme ',
'Neue Mainzer Str. ',
'Neue Mainzer Str. ',
'Neue Niedenau ',
'Neue Rothofstr. ',
'Neue Schlesingergasse ',
'Neuenhainer Str. ',
'Neuer Wall ',
'Neuer Weg ',
'Neufeldschneise ',
'Neugasse ',
'Neuhaußstr. ',
'Neuhofstr. ',
'Neulandstr. ',
'Neumannstr. ',
'Neumarkt ',
'Neunkircher Weg ',
'Neuwiesenschneise ',
'Neuwiesenstr. ',
'Nibelungenallee ',
'Nibelungenplatz ',
'Nidacorso ',
'Nidaforum ',
'Niddablick ',
'Niddagaustr. ',
'Niddastr. ',
'Nidderauer Str. ',
'Niedenau ',
'Nieder Kirchweg ',
'Niederbornstr. ',
'Niedererlenbacher Str. ',
'Niedereschbacher Stadtweg ',
'Niedereschbacher Str. ',
'Niedergärtenstr. ',
'Niedergasse ',
'Niedernhausener Str. ',
'Niederräder Brücke ',
'Niederräder Landstr. ',
'Niederräder Landstr. ',
'Niederräder Ufer ',
'Niederschbacher Stadtweg ',
'Niederschelder Weg ',
'Niederurseler Landstr. ',
'Niederurseler Steg ',
'Niedwiesenstr. ',
'Niemandsfeld ',
'Niersteiner Str. ',
'Nikolaus-Brum-Str. ',
'Nikolausstr. ',
'Nina-Rubinstein-Weg ',
'Nistergasse ',
'Nobelring ',
'Nonnenpfad ',
'Norbert-Wollheim-Platz ',
'Nordendplatz ',
'Nordendstr. ',
'Nordheimstr. ',
'Nordkreisel ',
'Nördlinger Weg ',
'Nordpassage ',
'Nordring ',
'Nürburgstr. ',
'Nürnberger Hof ',
'Nußbaumplatz ',
'Nußbaumstr. ',
'Nußgartenstr. ',
'Nußzeil ',
'Oase Der Stille ',
'Obere Burggasse ',
'Obere Kreuzäckerstr. ',
'Obere Rützelstr. ',
'Oberer Kalbacher Weg ',
'Oberer Kirchwiesenweg ',
'Oberer Ornberg ',
'Oberer Schafhofweg ',
'Oberfeldstr. ',
'Oberforsthausweg ',
'Oberhöchstädter Weg ',
'Oberlindau ',
'Obermainanlage ',
'Obermainstr. ',
'Obermühlgasse ',
'Obernhainer Str. ',
'Oberpfortenhof ',
'Oberräder Fußweg ',
'Oberschelder Weg ',
'Oberschweinstiege ',
'Oberschweinstiegschneise ',
'Obertshäuser Weg ',
'Oberurseler Weg ',
'Oberwaldschneise ',
'Oberweg ',
'Oberweid ',
'Oberwiesenstr. ',
'Oberwiesenweg ',
'Odenwaldstr. ',
'Odina-Bott-Platz ',
'Odrellstr. ',
'Oeder Weg ',
'Oeder Weg ',
'Oehlmühlgasse ',
'Oelmühlgasse ',
'Oeserstr. ',
'Oestricher Weg ',
'Offenbacher Landstr. ',
'Ohlengarten ',
'Ohmstr. ',
'Okrifteler Str. ',
'Olbrichstr. ',
'Olof-Palme-Str. ',
'Opernplatz ',
'Oppauer Weg ',
'Oppenheimer Landstr. ',
'Oppenheimer Landstr. ',
'Oppenheimer Str. ',
'Oranienstr. ',
'Orber Str. ',
'Ortenberger Str. ',
'Orthstr. ',
'Oskar-Schindler-Str. ',
'Oskar-Schindler-Weg ',
'Oskar-Schubert-Weg ',
'Oskar-Sommer-Str. ',
'Oskar-von-Miller-Str. ',
'Osloer Str. ',
'Ossietzkystr. ',
'Ostbahnhofstr. ',
'Ostendstr. ',
'Osthafenbrücke ',
'Osthafenplatz ',
'Ostparkstr. ',
'Ostparkstr. ',
'Ostpreußenstr. ',
'Oswaltstr. ',
'Ottilie-Wildermuth-Weg ',
'Otto-Brenner-Str. ',
'Otto-Ernst-Weg ',
'Otto-Fleck-Schneise ',
'Otto-Loewe-Str. ',
'Otto-Meßmer-Str. ',
'Otto-Schott-Str. ',
'Ottostr. ',
'Otzbergstr. ',
'Overbergstr. ',
'Palleskestr. ',
'Palmengartenstr. ',
'Palmstr. ',
'Pappelpfädchen ',
'Pappelpfädchen ',
'Paquetstr. ',
'Paradiesgasse ',
'Pariser Str. ',
'Parkhauseinfahrt ',
'Parkstr. ',
'Parlamentsplatz ',
'Parlamentsstr. ',
'Parrotweg ',
'Parsevalstr. ',
'Passavantstr. ',
'Paul-Apel-Str. ',
'Paul-Arnsberg-Platz ',
'Paul-Bode-Str. ',
'Paul-Ehrlich-Str. ',
'Paul-Gerhardt-Ring ',
'Paul-Heyse-Str. ',
'Paul-Kirchhof-Platz ',
'Paul-Kornfeld-Weg ',
'Paul-Schwerin-Str. ',
'Paul-Tillich-Str. ',
'Paul-Wempe-Allee ',
'Paulistr. ',
'Paulsplatz ',
'Peilschneise ',
'Pestalozziplatz ',
'Pestalozzistr. ',
'Peter-Behrens-Str. ',
'Peter-Bied-Str. ',
'Peter-Böhler-Str. ',
'Peter-Fischer-Allee ',
'Peter-Henlein-Str. ',
'Peter-Zenger-Str. ',
'Petersstr. ',
'Petterweilstr. ',
'Petunienweg ',
'Pfadfinderweg ',
'Pfaffenwiese ',
'Pfälzer Str. ',
'Pfannmüllerstr. ',
'Pfarrer-Perabo-Platz ',
'Pfarrgäßchen ',
'Pfeiferstr. ',
'Pferdskopfweg ',
'Pfingstbornstr. ',
'Pfingstbrunnenstr. ',
'Pfingstweidstr. ',
'Pflugspfad ',
'Pflugstr. ',
'Pfortengartenweg ',
'Pfortenstr. ',
'Pforzheimer Str. ',
'Pfungststr. ',
'Philipp-Fleck-Str. ',
'Philipp-Holzmann-Weg ',
'Philipp-Puth-Str. ',
'Philipp-Reis-Str. ',
'Philipp-Schnell-Str. ',
'Philippsruher Str. ',
'Philosophenweg ',
'Pirmasenser Str. ',
'Pissarroweg ',
'Platanenstr. ',
'Platanenweg ',
'Platenstr. ',
'Platenstr. ',
'Platz Der Einheit ',
'Platz Der Republik ',
'Plessengasse ',
'Plieningerstr. ',
'Polizeimeister-Kaspar-Str. ',
'Pommernstr. ',
'Porthstr. ',
'Porzellanhofstr. ',
'Poststr. ',
'Postweg ',
'Prächterstr. ',
'Prager Str. ',
'Prämäckerweg ',
'Praunheimer Brücke ',
'Praunheimer Hohl ',
'Praunheimer Landstr. ',
'Praunheimer Steg ',
'Praunheimer Weg ',
'Preungesheimer Str. ',
'Prießnitzstr. ',
'Prieststr. ',
'Propst-Goebels-Weg ',
'Prozessionsweg ',
'Pützerstr. ',
'Quäkerplatz ',
'Quellenstr. ',
'Querstr. ',
'Quirinsstr. ',
'Raabestr. ',
'Rabenkopfweg ',
'Radilostr. ',
'Raesfeldschneise ',
'Rahmhofstr. ',
'Raiffeisenstr. ',
'Raimundstr. ',
'Raimundstr. ',
'Rainweg ',
'Rangenbergstr. ',
'Ranzengasse ',
'Rappstr. ',
'Rapunzelgäßchen ',
'Rasselweg ',
'Rat-Beil-Str. ',
'Rathausgasse ',
'Rathaushof ',
'Rathenauplatz ',
'Ratsweg ',
'Ratswegbrücke ',
'Ratswegkreisel ',
'Rauenthaler Weg ',
'Raugasse ',
'Rauschenbachstr. ',
'Rauschenberger Str. ',
'Ravensteinstr. ',
'Rebenstr. ',
'Rebgärten ',
'Rebhuhnstr. ',
'Rebstöcker Str. ',
'Rebstöcker Weg ',
'Rechneigrabenstr. ',
'Reginastr. ',
'Rehbockschneise ',
'Rehstr. ',
'Reichelstr. ',
'Reichenbacher Weg ',
'Reichsburgstr. ',
'Reichsforststr. ',
'Reifenberger Str. ',
'Reinborner Weg ',
'Reineckstr. ',
'Reinganumstr. ',
'Reinhardstr. ',
'Rembrandtstr. ',
'Rendeler Str. ',
'Renettenstr. ',
'Rennbahnstr. ',
'Renneroder Str. ',
'Rennsteig ',
'Renoirallee ',
'Rethelstr. ',
'Reuterweg ',
'Reuterweg ',
'Reversbrunnenweg ',
'Rhaban-Fröhlich-Str. ',
'Rheinlandstr. ',
'Rheinstr. ',
'Rhonestr. ',
'Rhönstr. ',
'Rhönstr. ',
'Ribisweg ',
'Ribisweg ',
'Ricarda-Huch-Str. ',
'Richard-Biringer-Weg ',
'Richard-Breitenfeld-Str. ',
'Richard-Herrmann-Platz ',
'Richard-Strauss-Allee ',
'Richard-Wagner-Str. ',
'Richard-Weidlich-Platz ',
'Ricky-Adler-Str. ',
'Riedbergallee ',
'Riedbergplatz ',
'Riederhofstr. ',
'Riederspießstr. ',
'Riederwaldtunnel ',
'Riedhalsstr. ',
'Riedhofweg ',
'Riedrain ',
'Riedstr. ',
'Riedweg ',
'Rilkestr. ',
'Ringelnatzgässchen ',
'Ringelstr. ',
'Risselsteinweg ',
'Rita-Maiburg-Str. ',
'Robert-Blum-Str. ',
'Robert-Bosch-Str. ',
'Robert-Bunsen-Str. ',
'Robert-Dißmann-Str. ',
'Robert-Koch-Allee ',
'Robert-Mayer-Str. ',
'Robert-Mayer-Str. ',
'Rodbertusstr. ',
'Rödelheimer Bahnweg ',
'Rödelheimer Landstr. ',
'Rödelheimer Parkweg ',
'Rödelheimer Str. ',
'Rodelschneise ',
'Röderbergweg ',
'Röderbergweg ',
'Röderbergweg ',
'Röderichstr. ',
'Rodheimer Str. ',
'Roggengasse ',
'Rohlederstr. ',
'Rohmerplatz ',
'Rohmerstr. ',
'Rohrbachstr. ',
'Röhrborngasse ',
'Rohseeweg ',
'Rombergstr. ',
'Römerberg ',
'Römerstadtsteg ',
'Römerweg ',
'Römischer Ring ',
'Romroder Str. ',
'Ronneburgstr. ',
'Röntgenstr. ',
'Rosa-Luxemburg-Str. ',
'Rosa-Luxemburg-Str. ',
'Rosa-Marx-Weg ',
'Roßbachstr. ',
'Roscherstr. ',
'Roßdorfer Str. ',
'Roseggerstr. ',
'Rosenbergerstr. ',
'Rosengärtchen ',
'Rosengasse ',
'Rosenhof ',
'Roßkopfstr. ',
'Roßmarkt ',
'Rossertstr. ',
'Rossittener Str. ',
'Rostocker Str. ',
'Rotdornweg ',
'Rote-Kreuz-Weg ',
'Rotenbuschweg ',
'Roter Graben ',
'Roter Weg ',
'Rotfeder-Ring ',
'Rothschildallee ',
'Rothschildallee ',
'Rotkehlchenweg ',
'Rotlintstr. ',
'Rotteckstr. ',
'Rottweiler Platz ',
'Rottweiler Str. ',
'Rubensstr. ',
'Rückertstr. ',
'Rudolf-Amthauer-Str. ',
'Rudolf-Breitscheid-Str. ',
'Rudolf-Hilferding-Str. ',
'Rudolf-Presber-Str. ',
'Rudolf-Schwarz-Platz ',
'Rudolfstr. ',
'Rudolfstr. ',
'Rugierstr. ',
'Rühlstr. ',
'Rümelinstr. ',
'Rumpenheimer Str. ',
'Runkeler Str. ',
'Ruppertshainer Str. ',
'Ruprechtstr. ',
'Rüsselsheimer Str. ',
'Russingerstr. ',
'Rüsterstr. ',
'Ruth-Moufang-Str. ',
'Saalburgallee ',
'Saalburgstr. ',
'Saalfelder Str. ',
'Saalgasse ',
'Saalhof ',
'Saarbrücker Str. ',
'Sachsenhäuser Landwehrweg ',
'Sachsenhäuser Ufer ',
'Salmünsterer Str. ',
'Salvador-Allende-Str. ',
'Salzschlirfer Str. ',
'Samstagsberg ',
'Samstagsweg ',
'Sandäckerstr. ',
'Sandbrückschneise ',
'Sanddornweg ',
'Sandgasse ',
'Sandhöfer Allee ',
'Sandhofpassage ',
'Sandhofstr. ',
'Sandplackenstr. ',
'Sandweg ',
'Sankt-George-Str. ',
'Saonestr. ',
'Sauerackerweg ',
'Sauerstr. ',
'Saustegschneise ',
'Sausteigschneise ',
'Savignystr. ',
'Schadowstr. ',
'Schäfergasse ',
'Schäfers Gärten ',
'Schäferschneise ',
'Schäfflestr. ',
'Schafheckstr. ',
'Schalksbornstr. ',
'Schalksweg ',
'Schalkwiesenweg ',
'Schärfengäßchen ',
'Schaubstr. ',
'Schaumainkai ',
'Schaumainkai ',
'Schaumburger Str. ',
'Scheerengasse ',
'Scheerwaldschneise ',
'Scheffelstr. ',
'Scheidlachweg ',
'Scheidstr. ',
'Scheidswaldstr. ',
'Schellenbergstr. ',
'Schellgasse ',
'Schellingstr. ',
'Schelmenburgplatz ',
'Schelmenweg ',
'Schenckstr. ',
'Schenkendorfstr. ',
'Scherbelinoschneise ',
'Scherbiusstr. ',
'Schichaustr. ',
'Schielestr. ',
'Schießgraben ',
'Schießhüttenstr. ',
'Schifferstr. ',
'Schiller-Passage ',
'Schillerschneise ',
'Schillerstr. ',
'Schinkelstr. ',
'Schlagschneise ',
'Schlehenweg ',
'Schleidenstr. ',
'Schleiermacherstr. ',
'Schleifergasse ',
'Schlesierstr. ',
'Schleswiger Str. ',
'Schlettweinstr. ',
'Schleusenstr. ',
'Schleusenweg ',
'Schlickstr. ',
'Schliemannweg ',
'Schliephakestr. ',
'Schlinkenweg ',
'Schlitzer Str. ',
'Schloßborner Str. ',
'Schlosserstr. ',
'Schlossplatz ',
'Schloßstr. ',
'Schmalhardschneise ',
'Schmalkaldener Str. ',
'Schmickbrücke ',
'Schmickstr. ',
'Schmidtbornstr. ',
'Schmidtstr. ',
'Schmiedgasse ',
'Schmittener Str. ',
'Schnappbornweg ',
'Schneckenhofstr. ',
'Schneeballstr. ',
'Schneiderstr. ',
'Schneidhainer Str. ',
'Schneidmühlenweg ',
'Schneidwallgasse ',
'Schnepfenpfad ',
'Schöffenstr. ',
'Scholdererweg ',
'Schönberger Weg ',
'Schönblick ',
'Schönbornstr. ',
'Schöne Aussicht ',
'Schönecker Str. ',
'Schönhofstr. ',
'Schönstr. ',
'Schönwetterstr. ',
'Schopenhauerstr. ',
'Schottener Str. ',
'Schottensteinschneise ',
'Schottensteinschneise ',
'Schottensteinstr. ',
'Schreberweg ',
'Schreinerstr. ',
'Schreyerstr. ',
'Schrimpegasse ',
'Schubertstr. ',
'Schulstr. ',
'Schultheißenweg ',
'Schulze-Delitzsch-Str. ',
'Schumannstr. ',
'Schüttenhelmweg ',
'Schüttgrabenstr. ',
'Schützenbleiche ',
'Schützenhausweg ',
'Schützenhüttenweg ',
'Schützenschneise ',
'Schützenstr. ',
'Schwabstr. ',
'Schwagerstr. ',
'Schwalbacher Str. ',
'Schwalbenweg ',
'Schwälmer Str. ',
'Schwanenstr. ',
'Schwanheimer Bahnstr. ',
'Schwanheimer Brücke ',
'Schwanheimer Str. ',
'Schwanheimer Str. ',
'Schwanheimer Ufer ',
'Schwanheimer Weg ',
'Schwanthalerstr. ',
'Schwanthalerstr. ',
'Schwarzbachstr. ',
'Schwarzburgstr. ',
'Schwarzer Weg ',
'Schwarzerlenweg ',
'Schwarzsteinkautweg ',
'Schwarzwaldstr. ',
'Schwedenkronenplatz ',
'Schwedenpfad ',
'Schwedenschanzenschneise ',
'Schwedlerbrücke ',
'Schwedlerbrücke ',
'Schwedlerstr. ',
'Schwedlerweg ',
'Schweinfurter Weg ',
'Schweizer Platz ',
'Schweizer Str. ',
'Schwertfegergäßchen ',
'Schwertmannstr. ',
'Schwesternstr. ',
'Schwindstr. ',
'Sebastian-Kneipp-Str. ',
'Sebastian-Rinz-Str. ',
'Seckbacher Bitzweg ',
'Seckbächer Gasse ',
'Seckbacher Klemmenweg ',
'Seckbacher Kreuzweg ',
'Seckbacher Landstr. ',
'Sedanstr. ',
'Seebachstr. ',
'Seegewann ',
'Seeheimer Str. ',
'Seehofstr. ',
'Seehofsweg ',
'Seelenberger Str. ',
'Seibelweg ',
'Seibertsgasse ',
'Seidelbaststr. ',
'Seilerbahn ',
'Seilerstr. ',
'Selma-Lagerlöf-Str. ',
'Selzerbrunnenweg ',
'Senckenberganlage ',
'Senefelderweg ',
'Serviceweg Startbahn Nord-West ',
'Seulberger Str. ',
'Seumestr. ',
'Severusstr. ',
'Siboldgasse ',
'Siebenbürgenstr. ',
'Siedlerstr. ',
'Siegener Str. ',
'Siegfried-Gößling-Weg ',
'Siemensstr. ',
'Sieringstr. ',
'Siesmayerstr. ',
'Sigmund-Freud-Str. ',
'Silberbornstr. ',
'Silcherstr. ',
'Silostr. ',
'Simon-Ochs-Str. ',
'Simsonstr. ',
'Sindlinger Bahnstr. ',
'Sindlinger Mainbrücke ',
'Sindlinger Str. ',
'Sinner Weg ',
'Siolistr. ',
'Sirenenstr. ',
'Skylineblick ',
'Sodener Str. ',
'Solmsstr. ',
'Sömmerringstr. ',
'Sondershausenstr. ',
'Sonnemannstr. ',
'Sonnenhof ',
'Sonnentaustr. ',
'Sonnenweg ',
'Sontraer Str. ',
'Soonwaldstr. ',
'Sophie-Rosenthal-Str. ',
'Sophie-Von-La-Roche-Weg ',
'Sophienstr. ',
'Sorbenstr. ',
'Sossenheimer Kirchberg ',
'Sossenheimer Mühlgasse ',
'Sossenheimer Riedstr. ',
'Sossenheimer Weg ',
'Souchaystr. ',
'Spatzengasse ',
'Speckgäßchen ',
'Speckgasse ',
'Speckweg ',
'Speicherstr. ',
'Speierlingweg ',
'Spenerstr. ',
'Sperberschneise ',
'Sperberweg ',
'Spessarteichenweg ',
'Spessartstr. ',
'Speyerer Str. ',
'Spielmannstr. ',
'Spielsgasse ',
'Spitzbubenweg ',
'Spitzenstr. ',
'Spitzgartenweg ',
'Spohrstr. ',
'St.-George-Str. ',
'Städelstr. ',
'Stadion ',
'Stalburgstr. ',
'Starenweg ',
'Stargarder Str. ',
'Starkenburger Str. ',
'Staufenstr. ',
'Stefan-Zweig-Str. ',
'Stegerwaldstr. ',
'Stegstr. ',
'Stegweidhof ',
'Steigschneise ',
'Steigweg ',
'Steinäckerstr. ',
'Steinauer Str. ',
'Steinbacher Hohl ',
'Steingrundschneise ',
'Steingrundweg ',
'Steinhausenstr. ',
'Steinkleestr. ',
'Steinkopfweg ',
'Steinlestr. ',
'Steinmetzstr. ',
'Steinritzstr. ',
'Steinrutsch ',
'Steinstr. ',
'Steinweg ',
'Steinweg ',
'Steinweg-Passage ',
'Stephan-Heise-Str. ',
'Stephanstr. ',
'Stephensonstr. ',
'Sterlepperstr. ',
'Sternstr. ',
'Stettenstr. ',
'Stettiner Str. ',
'Steuernagelstr. ',
'Stichelstr. ',
'Stichgärtenstr. ',
'Stichlingstr. ',
'Stieglitzenweg ',
'Stierstädter Str. ',
'Stiftstr. ',
'Stiftung-Waisenhaus-Weg ',
'Stockheimer Str. ',
'Stockholmer Str. ',
'Stoltzeschneise ',
'Stoltzestr. ',
'Stöppelschneise ',
'Storchgasse ',
'Strahlenberger Weg ',
'Stralsunder Str. ',
'Straßburger Str. ',
'Str. Der Nationen ',
'Str. Zur Internationalen Schule ',
'Straßheimstr. ',
'Stresemannallee ',
'Stroofstr. ',
'Strubbergstr. ',
'Stupanusstr. ',
'Stuttgarter Str. ',
'Stützeläckerweg ',
'Südallee ',
'Sudermannstr. ',
'Sudetenstr. ',
'Südkreisel ',
'Südpassage ',
'Sulzbacher Str. ',
'Tacitusstr. ',
'Tagetesweg ',
'Taläckerstr. ',
'Talschneise ',
'Talstr. ',
'Tannenhof ',
'Tannenkopfweg ',
'Tannenwaldstr. ',
'Tannenweg ',
'Tarnowitzer Str. ',
'Taschnerstr. ',
'Taubenlachschneise ',
'Taubenstr. ',
'Taufsteinweg ',
'Taunusanlage ',
'Taunusblick ',
'Taunusstr. ',
'Taunustor ',
'Taunustor ',
'Taxistand ',
'Taxistr. ',
'Teichstr. ',
'Telemannstr. ',
'Tellerweg ',
'Tempelgasse ',
'Teplitz-Schönauer-Str. ',
'Terminal 1 a to B Tunnel ',
'Teutonenweg ',
'Tevesstr. ',
'Textorstr. ',
'The Squaire ',
'Thea-Rasche-Str. ',
'Theatertunnel ',
'Theobald-Christ-Str. ',
'Theobald-Ziegler-Str. ',
'Theodor-Fischer-Weg ',
'Theodor-Haubach-Weg ',
'Theodor-Heuss-Allee ',
'Theodor-Neubürger-Str. ',
'Theodor-Stern-Kai ',
'Theodor-Storm-Str. ',
'Theodor-Thomas-Str. ',
'Theodor-W.-Adorno-Platz ',
'Therese-Herger-Anlage ',
'Thielenstr. ',
'Thiotmannstr. ',
'Thomas-Mann-Str. ',
'Thomasiusstr. ',
'Thomestr. ',
'Thorwaldsenplatz ',
'Thorwaldsenstr. ',
'Throner Str. ',
'Thudichumstr. ',
'Thünenstr. ',
'Thüringer Str. ',
'Thurn-und-Taxis-Platz ',
'Tiberiusstr. ',
'Tiefgarage ',
'Tilly-Edinger-Platz ',
'Tillystr. ',
'Tilsiter Str. ',
'Tiroler Park ',
'Tiroler Schneise ',
'Tiroler Str. ',
'Tischbeinstr. ',
'Tituscorso ',
'Titusstr. ',
'Töngesgasse ',
'Toni-Sender-Str. ',
'Töplitzstr. ',
'Tornowstr. ',
'Trajanstr. ',
'Trakehner Str. ',
'Tränkschneise ',
'Tränkweg ',
'Tränkweg ',
'Treburer Str. ',
'Treisberger Str. ',
'Treunerweg ',
'Trichterfeldschneise ',
'Triebstr. ',
'Trifelsstr. ',
'Triftstr. ',
'Trümpertstr. ',
'Tucholskystr. ',
'Tulpenweg ',
'Tunnelweg ',
'Turiner Str. ',
'Turmstr. ',
'Turnerschneise ',
'Turnschulschneise ',
'Über den Gartenwiesen ',
'Über Der Heiern ',
'Überlinger Weg ',
'Uhlandstr. ',
'Uhlfelderstr. ',
'Ulmenstr. ',
'Ulrichstr. ',
'Unter den Akazien ',
'Unter den Birken ',
'Unter den Buchen ',
'Unter den Eichen ',
'Unter den Eschen ',
'Unter den Kastanien ',
'Unter den Linden ',
'Unter den Platanen ',
'Unter der Friedensbrücke ',
'Untere Burggasse ',
'Untere Rützelstr. ',
'Unterer Atzemer ',
'Unterer Kalbacher Weg ',
'Unterer Kirchwiesenweg ',
'Unterführung Hinkelsteinschneise ',
'Unterlindau ',
'Untermainanlage ',
'Untermainbrücke ',
'Untermainkai ',
'Untermainkai ',
'Unterschweinstiege ',
'Unterschweinstiegschneise ',
'Unterster Zwerchweg ',
'Unterwaldschneise ',
'Unterweg ',
'Urnbergweg ',
'Urseler Weg ',
'Ursinusstr. ',
'Usastr. ',
'Usinger Str. ',
'Utrilloweg ',
'Valentin-Schmetzer-Weg ',
'Valentin-Senger-Str. ',
'Varrentrappstr. ',
'Vatterstr. ',
'Vereinsstr. ',
'Verlängerte Hedderichstr. ',
'Verlängerter Gruftenweg ',
'Victor-Gollancz-Weg ',
'Victor-Slotosch-Str. ',
'Viehtrieb ',
'Vierhäusergasse ',
'Vierherrnsteinschneise ',
'Vilbeler Landstr. ',
'Vilbeler Landstr. ',
'Vilbeler Str. ',
'Voelckerstr. ',
'Vogelsbergstr. ',
'Vogelschneise ',
'Vogelstr. ',
'Vogelwartenweg ',
'Vogelweidstr. ',
'Vogesenstr. ',
'Vogtstr. ',
'Volgersbrunnenweg ',
'Völklinger Weg ',
'Volkshausstr. ',
'Volpenhennstr. ',
'Voltastr. ',
'Voltenseestr. ',
'Voltenseeweg ',
'Vorm Wald ',
'Wacholderweg ',
'Wachtelweg ',
'Wächtersbacher Str. ',
'Wagengasse ',
'Wagenweg ',
'Waidmannstr. ',
'Waitzstr. ',
'Walburga-Zizka-Weg ',
'Waldauschneise ',
'Waldecker Str. ',
'Waldemser Str. ',
'Waldfriedstr. ',
'Waldlehrpfad Schwanheim ',
'Waldmeisterpfad ',
'Waldschmidtstr. ',
'Waldschulstr. ',
'Waldstr. ',
'Wallauer Str. ',
'Walldorfer Str. ',
'Wallfahrtsweg ',
'Wallstr. ',
'Walnußweg ',
'Walter-Abschlag-Weg ',
'Walter-Gropius-Str. ',
'Walter-Hesselbach-Str. ',
'Walter-Kolb-Str. ',
'Walter-Leiske-Str. ',
'Walter-Möller-Platz ',
'Walter-Schwagenscheidt-Platz ',
'Walter-Vom-Rath-Str. ',
'Walther-Nernst-Str. ',
'Walther-von-Cronberg-Platz ',
'Wanebachstr. ',
'Wanzenschneise ',
'Warschauer Str. ',
'Wartburgstr. ',
'Wartegäßchen (zweites) ',
'Warthweg ',
'Warthweg ',
'Wartschneise ',
'Wasgaustr. ',
'Wasserhofstr. ',
'Wasserlehrpfad ',
'Wasserleitungsweg ',
'Wasserturmweg ',
'Wasserweg ',
'Wasserwerk Griesheim ',
'Weberstr. ',
'Weckerlinstr. ',
'Weckmarkt ',
'Wed ',
'Wegscheidestr. ',
'Wehrheimer Str. ',
'Wehrhofstr. ',
'Wehrstr. ',
'Weibleinsgasse ',
'Weidenauer Str. ',
'Weidenbornstr. ',
'Weidenbornstr. ',
'Weiherhof ',
'Weiherstr. ',
'Weiherweg ',
'Weilbacher Str. ',
'Weilbrunnstr. ',
'Weilburger Str. ',
'Weimarer Str. ',
'Weinbergstr. ',
'Weingärtenanlage ',
'Weinstr. ',
'Weißadlergasse ',
'Weisbachstr. ',
'Weißdornweg ',
'Weißenackerschneise ',
'Weißfrauenstr. ',
'Weißkirchener Weg ',
'Weismüllerstr. ',
'Weisser Hirsch Weg ',
'Weißtannenweg ',
'Weizengasse ',
'Wellengasse ',
'Welscher Weg ',
'Welschgrabenstr. ',
'Wendelsweg ',
'Wenzelweg ',
'Werftstr. ',
'Werksbrücke Mitte ',
'Werner-Bockelmann-Str. ',
'Werner-Haustein-Str. ',
'Werrastr. ',
'Wertheimer Str. ',
'Weserstr. ',
'West-Höchster Str. ',
'Westenbergerstr. ',
'Westendplatz ',
'Westendstr. ',
'Westerbachstr. ',
'Westerbachstr. ',
'Westerwaldstr. ',
'Westhafen ',
'Westhafenbrücke ',
'Westhafenplatz ',
'Westlicher Ringweg ',
'Westpreußenstr. ',
'Westring ',
'Wetteraustr. ',
'Wetzlarer Str. ',
'Wichernstr. ',
'Wickenweg ',
'Wicker-Frosch-Str. ',
'Wickerer Str. ',
'Wielandstr. ',
'Wiener Pfad ',
'Wiener Str. ',
'Wiesbadener Str. ',
'Wiesenau ',
'Wiesenfeldstr. ',
'Wiesenhüttenplatz ',
'Wiesenhüttenstr. ',
'Wiesenstr. ',
'Wildenbruchstr. ',
'Wildentenstr. ',
'Wildgäßchen ',
'Wildunger Str. ',
'Wilhelm-Beckel-Str. ',
'Wilhelm-Beer-Weg ',
'Wilhelm-Busch-Str. ',
'Wilhelm-Epstein-Str. ',
'Wilhelm-Fay-Str. ',
'Wilhelm-Flögel-Ring ',
'Wilhelm-Grandhomme-Str. ',
'Wilhelm-Grandhomme-Str. ',
'Wilhelm-Gutbrod-Str. ',
'Wilhelm-Hauff-Str. ',
'Wilhelm-Kobelt-Str. ',
'Wilhelm-Koch-Weg ',
'Wilhelm-Koppel-Weg ',
'Wilhelm-Leuschner-Str. ',
'Wilhelm-Meiß-Str. ',
'Wilhelm-Roser-Weg ',
'Wilhelm-Schickard-Str. ',
'Wilhelm-Schmelz-Weg ',
'Wilhelmine-Reichard-Weg ',
'Wilhelmsbader Weg ',
'Wilhelmshavener Str. ',
'Wilhelmshöher Str. ',
'Willemerstr. ',
'Willemineallee ',
'Willibrachtstr. ',
'Willmannstr. ',
'Willy-Berking-Str. ',
'Willy-Brandt-Platz ',
'Willy-Sedler-Weg ',
'Wim-Duisenberg-Platz ',
'Windeckstr. ',
'Windmühlstr. ',
'Windthorststr. ',
'Wingertstr. ',
'Winkelgasse ',
'Winterbachstr. ',
'Winterstr. ',
'Winzersteige ',
'Wirschelweg ',
'Wismarer Str. ',
'Wittelsbacherallee ',
'Wittelsbacherallee ',
'Wöhlerstr. ',
'Wolf-Heidenheim-Str. ',
'Wolfgang-Bangert-Str. ',
'Wolfhagener Str. ',
'Wolfsgangstr. ',
'Wolfshohl ',
'Wolfsweg ',
'Wöllstädter Str. ',
'Woogstr. ',
'Wörbachstr. ',
'Wormser Str. ',
'Wörsdorfer Str. ',
'Wurmbachstr. ',
'Würzburger Str. ',
'Wurzelstr. ',
'Xaver-Fendt-Str. ',
'Zanderstr. ',
'Zaunstr. ',
'Zehnmorgenstr. ',
'Zehntgasse ',
'Zehnthofgasse ',
'Zeil ',
'Zeil ',
'Zeilweg ',
'Zeißelstr. ',
'Zeisigweg ',
'Zelterstr. ',
'Zentgrafenstr. ',
'Zentmarkweg ',
'Zeppelinallee ',
'Zeppelinallee ',
'Zeuläckerstr. ',
'Ziegelei-Allee ',
'Ziegelgasse ',
'Ziegelhüttenplatz ',
'Ziegelhüttenweg ',
'Ziegenhainer Str. ',
'Zillestr. ',
'Zimmerweg ',
'Zinzendorfweg ',
'Zobelstr. ',
'Zorbachstr. ',
'Zuckschwerdtstr. ',
'Zugang Zu Den Häusern 65 65a 67 67a ',
'Zum Apothekerhof ',
'Zum Bergwerk ',
'Zum Brommenhof ',
'Zum Eiskeller ',
'Zum Erlengrund ',
'Zum Eschbachsteg ',
'Zum Gipelhof ',
'Zum Goetheturm ',
'Zum Gottschalkhof ',
'Zum Heidebuckel ',
'Zum Laurenburger Hof ',
'Zum Linnegraben ',
'Zum Margarethenzehnten ',
'Zum Messeparkhaus Rebstock ',
'Zum Pfarrturm ',
'Zum Rebstockbad ',
'Zum Schäferköppel ',
'Zum Schlegelhof ',
'Zum Schlinkenborn ',
'Zum Stulen ',
'Zum Taubenzehnten ',
'Zum-Jungen-Str. ',
'Zur Bornfloßquelle ',
'Zur Charlottenburg ',
'Zur Frankenfurt ',
'Zur Friedenseiche ',
'Zur Kalbacher Höhe ',
'Zur Obermühle ',
'Zur Untermühle ',
'Zur Waldau ',
'Züricher Str. ',
'Zweites Altebergsgäßchen ',
'Zweites Wartegäßchen ',
'Zwingergasse ',
'Zwischenstr. '
];


var bekannte = ['Ernie', 'Knarzi', 'Pfiffi', 'Pengo'];

var alteBekannte = Object.assign([], bekannte);


var nach = [... new Set(vor)];
console.log(nach);

const dauer = Date.now() - startZeit;
console.log(dauer);

